In [1]:
print("hello")

hello

In [2]:
!pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\users\admin\appdata\roaming\python\python313\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\admin\appdata\roaming\python\python313\site-packages (from pandas) (2.2.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\admin\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\admin\appdata\roaming\python\python313\site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\admin\appdata\roaming\python\python313\site-packages (from pandas) (2024.2)
Requirement already satisfied: six>=1.5 in c:\users\admin\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.1.1 -> 26.2.1
[notice] To update, run: C:\Program Files\Python313\python.exe -m pip install --upgrade pip

In [3]:
import numpy as np
import pandas as pd

In [4]:
a = np.array([[1, 2, 3], [4, 5, 6]])

In [5]:
a.shape

(2, 3)

In [6]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# Series : one column from a table

In [8]:
countries = ["India", "USA", "Germany", "France", "UK"]

In [10]:
series_data = pd.Series(countries)

In [11]:
series_data

0      India
1        USA
2    Germany
3     France
4         UK
dtype: object

In [12]:
runs = [10, 50, 70, 80, 45]

In [13]:
pd.Series(runs)

0    10
1    50
2    70
3    80
4    45
dtype: int64

In [14]:
marks = [67, 57, 90, 100]
subject = ['english', 'hindi', 'science', 'maths']

In [16]:
pd.Series(marks, index = subject, name = 'Tushar marks')

english     67
hindi       57
science     90
maths      100
Name: Tushar marks, dtype: int64

In [17]:
marks = {
    'maths' : 89, 
    'science' : 90,
    'hindi' : 79, 
    'english' : 80 
}

In [19]:
marks = pd.Series(marks)

In [20]:
marks.size

4

In [21]:
marks.dtype

dtype('int64')

In [23]:
print(marks.name)

None

In [24]:
marks.is_unique

True

In [26]:
marks.shape

(4,)

In [ ]:
# csv : comma seperated values

In [41]:
data = pd.read_csv(r"C:\Users\Admin\Desktop\projects\Data Science-1pm\Pandas\insurance.csv")

In [30]:
type(insurance_data)

pandas.core.frame.DataFrame

In [31]:
insurance_data

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [32]:
insurance_data.shape

(1338, 7)

In [33]:
insurance_data.size

9366

In [40]:
insurance_data.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [38]:
insurance_data.tail()

      age     sex    bmi  children smoker     region     charges
1333   50    male  30.97         3     no  northwest  10600.5483
1334   18  female  31.92         0     no  northeast   2205.9808
1335   18  female  36.85         0     no  southeast   1629.8335
1336   21  female  25.80         0     no  southwest   2007.9450
1337   61  female  29.07         0    yes  northwest  29141.3603

In [42]:
data.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [43]:
data.tail()

      age     sex    bmi  children smoker     region     charges
1333   50    male  30.97         3     no  northwest  10600.5483
1334   18  female  31.92         0     no  northeast   2205.9808
1335   18  female  36.85         0     no  southeast   1629.8335
1336   21  female  25.80         0     no  southwest   2007.9450
1337   61  female  29.07         0    yes  northwest  29141.3603

In [44]:
data.dtypes

age           int64
sex          object
bmi         float64
children      int64
smoker       object
region       object
charges     float64
dtype: object

In [45]:
data.index

RangeIndex(start=0, stop=1338, step=1)

In [47]:
for col in data.columns:
    print(col)

age
sex
bmi
children
smoker
region
charges

In [48]:
data

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [50]:
type(data.values)

numpy.ndarray

In [51]:
data

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [52]:
data.sample(10)

      age     sex     bmi  children smoker     region      charges
1159   32  female  41.100         0     no  southwest   3989.84100
732    24  female  30.100         3     no  southwest   4234.92700
191    36  female  26.200         0     no  southwest   4883.86600
534    64    male  40.480         0     no  southeast  13831.11520
806    40  female  41.420         1     no  northwest  28476.73499
1185   45    male  23.560         2     no  northeast   8603.82340
1275   57    male  23.700         0     no  southwest  10959.33000
1290   38  female  19.950         2     no  northeast   7133.90250
1088   52    male  47.740         1     no  southeast   9748.91060
554    25  female  41.325         0     no  northeast  17878.90068

In [53]:
data.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [56]:
data.iloc[0].shape

(7,)

In [57]:
ann = data.values

In [58]:
ann

array([[19, 'female', 27.9, ..., 'yes', 'southwest', 16884.924],
       [18, 'male', 33.77, ..., 'no', 'southeast', 1725.5523],
       [28, 'male', 33.0, ..., 'no', 'southeast', 4449.462],
       ...,
       [18, 'female', 36.85, ..., 'no', 'southeast', 1629.8335],
       [21, 'female', 25.8, ..., 'no', 'southwest', 2007.945],
       [61, 'female', 29.07, ..., 'yes', 'northwest', 29141.3603]],
      dtype=object)

In [59]:
ann[0]

array([19, 'female', 27.9, 0, 'yes', 'southwest', 16884.924], dtype=object)

In [60]:
data

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [61]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   object
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   object
 5   region    1338 non-null   object
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB

In [62]:
data.describe()

               age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

In [63]:
# find the total number of numerical and categorical col from the data

In [67]:
numerical_col = []
categorical_col = []
for col in data.columns:
    if data[col].dtype != object:
        numerical_col.append(col)
    else:
        categorical_col.append(col)
print(f"Number of categorical col {len(categorical_col)} and Number of numerical col {len(numerical_col)}")

Number of categorical col 3 and Number of numerical col 4

In [66]:
data['age'].dtype

dtype('int64')

In [69]:
data.isnull().mean()

age         0.0
sex         0.0
bmi         0.0
children    0.0
smoker      0.0
region      0.0
charges     0.0
dtype: float64

In [70]:
# age : 100 - 10
# 10/100

In [71]:
data.duplicated().sum()

1

In [75]:
data['age'].unique()

array([19, 18, 28, 33, 32, 31, 46, 37, 60, 25, 62, 23, 56, 27, 52, 30, 34,
       59, 63, 55, 22, 26, 35, 24, 41, 38, 36, 21, 48, 40, 58, 53, 43, 64,
       20, 61, 44, 57, 29, 45, 54, 49, 47, 51, 42, 50, 39], dtype=int64)

In [76]:
data['region'].unique()

array(['southwest', 'southeast', 'northwest', 'northeast'], dtype=object)

In [77]:
data['sex'].unique()

array(['female', 'male'], dtype=object)

In [82]:
data = data.rename(columns = {'AGE' : 'age'})

In [83]:
data

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [84]:
# indexing and slicing

In [85]:
data.iloc[0]

age                19
sex            female
bmi              27.9
children            0
smoker            yes
region      southwest
charges     16884.924
Name: 0, dtype: object

In [88]:
d = {'a' : 10, 'b': 20}

d['a']

10

In [86]:
data['age']

0       19
1       18
2       28
3       33
4       32
        ..
1333    50
1334    18
1335    18
1336    21
1337    61
Name: age, Length: 1338, dtype: int64

In [90]:
data.iloc[0, 1: 5]

sex         female
bmi           27.9
children         0
smoker         yes
Name: 0, dtype: object

In [94]:
data.iloc[10 : 100, 2: 6]

      bmi  children smoker     region
10  26.22         0     no  northeast
11  26.29         0    yes  southeast
12  34.40         0     no  southwest
13  39.82         0     no  southeast
14  42.13         0    yes  southeast
..    ...       ...    ...        ...
95  37.62         1     no  southeast
96  30.80         3     no  southwest
97  38.28         0     no  southeast
98  19.95         0    yes  northeast
99  19.30         0    yes  southwest

[90 rows x 4 columns]

In [95]:
data['age']

0       19
1       18
2       28
3       33
4       32
        ..
1333    50
1334    18
1335    18
1336    21
1337    61
Name: age, Length: 1338, dtype: int64

In [96]:
data

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [97]:
data[['age', 'region', 'charges', 'sex']]

      age     region      charges     sex
0      19  southwest  16884.92400  female
1      18  southeast   1725.55230    male
2      28  southeast   4449.46200    male
3      33  northwest  21984.47061    male
4      32  northwest   3866.85520    male
...   ...        ...          ...     ...
1333   50  northwest  10600.54830    male
1334   18  northeast   2205.98080  female
1335   18  southeast   1629.83350  female
1336   21  southwest   2007.94500  female
1337   61  northwest  29141.36030  female

[1338 rows x 4 columns]

In [98]:
data.iloc[100]

age                41
sex            female
bmi              31.6
children            0
smoker             no
region      southwest
charges      6186.127
Name: 100, dtype: object

In [99]:
data.loc[100]

age                41
sex            female
bmi              31.6
children            0
smoker             no
region      southwest
charges      6186.127
Name: 100, dtype: object

In [105]:
marks.loc['maths']

89

In [106]:
marks

maths      89
science    90
hindi      79
english    80
dtype: int64

In [20]:
import pandas as pd
import numpy as np

data = pd.read_csv(r"C:\Users\Admin\Desktop\projects\Data Science-1pm\Pandas\insurance.csv")
# pd.read_csv?

In [21]:
data

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [22]:
data.iloc[100]

age                41
sex            female
bmi              31.6
children            0
smoker             no
region      southwest
charges      6186.127
Name: 100, dtype: object

In [23]:
data.loc["yes"]

KeyError: 'yes'

In [24]:
data.describe()

               age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

In [25]:
# data filter

# find the number of customer belong to southwest

In [26]:
data

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [32]:
print(f'Number of customer from southwest region are {data[data["region"] == "southwest"].shape[0]}')

Number of customer from southwest region are 325

In [34]:
data.sample(10)

      age     sex     bmi  children smoker     region      charges
1187   62  female  32.680         0     no  northwest  13844.79720
728    18  female  40.280         0     no  northeast   2217.60120
80     31    male  26.885         1     no  northeast   4441.21315
77     21    male  35.530         0     no  southeast   1532.46970
1186   20    male  35.625         3    yes  northwest  37465.34375
785    35  female  27.700         3     no  southwest   6414.17800
213    34  female  26.730         1     no  southeast   5002.78270
1252   20    male  27.300         0    yes  southwest  16232.84700
979    36  female  29.920         0     no  southeast   4889.03680
1146   60    male  32.800         0    yes  southwest  52590.82939

In [35]:
# find the number of customer who are female and male

In [45]:
for sex_type in data['sex'].unique():
    print(f'Number of {sex_type}s are {data[data["sex"] == sex_type].shape[0]}')
    print()

Number of females are 662

Number of males are 676

In [50]:
print(f'Average bmi : {np.round(data["bmi"].mean(), 4)}')

Average bmi : 30.6634

In [51]:
# maths function
data['age'].mean()

39.20702541106129

In [52]:
data['age'].median()

39.0

In [54]:
data['age'].std()

14.049960379216154

In [55]:
data['age'].var()

197.40138665754375

In [56]:
data['age'].count()

1338

In [57]:
data

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [58]:
# find the total female customer from southwest region

In [64]:
data[(data['sex'] == 'female')  & (data['region'] == 'southwest')]

      age     sex   bmi  children smoker     region      charges
0      19  female  27.9         0    yes  southwest  16884.92400
21     30  female  32.4         1     no  southwest   4149.73600
32     19  female  28.6         5     no  southwest   4687.79700
65     19  female  28.9         0     no  southwest   1743.21400
66     61  female  39.1         2     no  southwest  14235.07200
...   ...     ...   ...       ...    ...        ...          ...
1313   19  female  34.7         2    yes  southwest  36397.57600
1316   19  female  20.6         0     no  southwest   1731.67700
1331   23  female  33.4         0     no  southwest  10795.93733
1332   52  female  44.7         3     no  southwest  11411.68500
1336   21  female  25.8         0     no  southwest   2007.94500

[162 rows x 7 columns]

In [65]:
data.sample(20)

      age     sex     bmi  children smoker     region      charges
838    35  female  23.465         2     no  northeast   6402.29135
1056   48  female  28.900         0     no  southwest   8277.52300
495    20    male  27.930         0     no  northeast   1967.02270
529    18    male  25.460         0     no  northeast   1708.00140
888    22    male  39.500         0     no  southwest   1682.59700
731    53    male  21.400         1     no  southwest  10065.41300
409    32    male  30.030         1     no  southeast   4074.45370
442    18    male  43.010         0     no  southeast   1149.39590
599    52  female  37.525         2     no  northwest  33471.97189
1337   61  female  29.070         0    yes  northwest  29141.36030
1000   30    male  22.990         2    yes  northwest  17361.76610
1166   57    male  40.370         0     no  southeast  10982.50130
558    35  female  34.105         3    yes  northwest  39983.42595
663    18    male  33.660         0     no  southeast   1136.39940
1062   59    male  41.140         1    yes  southeast  48970.24760
60     43    male  27.360         3     no  northeast   8606.21740
976    48    male  40.150         0     no  southeast   7804.16050
268    45    male  30.200         1     no  southwest   7441.05300
661    57  female  23.980         1     no  southeast  22192.43711
398    64    male  25.600         2     no  southwest  14988.43200

In [69]:
# find the average charge of male

print(data[data['sex'] == 'male']['charges'].mean())
print(data[data['sex'] == 'female']['charges'].mean())

13956.751177721893
12569.578843835347

In [74]:
data['sex'].value_counts().reset_index()

      sex  count
0    male    676
1  female    662

In [75]:
data.sample(10)

      age     sex     bmi  children smoker     region      charges
1249   32    male  33.630         1    yes  northeast  37607.52770
925    50    male  32.110         2     no  northeast  25333.33284
1101   53    male  28.600         3     no  southwest  11253.42100
934    32    male  37.180         2     no  southeast   4673.39220
98     56    male  19.950         0    yes  northeast  22412.64850
774    41    male  34.200         2     no  northwest   7261.74100
701    50  female  44.745         0     no  northeast   9541.69555
668    62    male  32.015         0    yes  northeast  45710.20785
87     56  female  27.200         0     no  southwest  11073.17600
420    64    male  33.880         0    yes  southeast  46889.26120

In [80]:
data[(data['children'] >= 2)  & (data['region'] == 'southwest') & (data['age'] > 35)  & (data['age'] <= 50)]

      age     sex   bmi  children smoker     region      charges
74     44    male  27.4         2     no  southwest   7726.85400
84     37  female  34.8         2    yes  southwest  39836.51900
120    44    male  37.1         2     no  southwest   7740.33700
129    38    male  34.7         2     no  southwest   6082.40500
178    46  female  28.9         2     no  southwest   8823.27900
214    45  female  30.9         2     no  southwest   8520.02600
215    41  female  37.1         2     no  southwest   7371.77200
243    40    male  35.3         3     no  southwest   7196.86700
271    50    male  34.2         2    yes  southwest  42856.83800
396    43  female  34.4         3     no  southwest   8522.00300
417    36  female  22.6         2    yes  southwest  18608.26200
424    48    male  30.2         2     no  southwest   8968.33000
450    39    male  29.6         4     no  southwest   7512.26700
484    48    male  34.3         3     no  southwest   9563.02900
497    45    male  28.7         2     no  southwest   8027.96800
537    46  female  30.2         2     no  southwest   8825.08600
568    49  female  31.9         5     no  southwest  11552.90400
598    43    male  32.6         2     no  southwest   7441.50100
611    38  female  34.8         2     no  southwest   6571.54400
617    49    male  25.6         2    yes  southwest  23306.54700
621    37    male  34.1         4    yes  southwest  40182.24600
682    39    male  35.3         2    yes  southwest  40103.89000
810    46  female  30.8         3     no  southwest   9414.92000
860    37  female  47.6         2    yes  southwest  46113.51100
861    38  female  28.0         3     no  southwest   7151.09200
865    40    male  29.9         2     no  southwest   6600.36100
879    37  female  29.5         2     no  southwest   6311.95200
932    46    male  25.8         5     no  southwest  10096.97000
946    42    male  35.8         2     no  southwest   7160.09400
953    44    male  30.2         2    yes  southwest  38998.54600
992    50  female  31.6         2     no  southwest  10118.42400
996    39  female  34.1         3     no  southwest   7418.52200
1053   47    male  29.8         3    yes  southwest  25309.48900
1085   39  female  18.3         5    yes  southwest  19023.26000
1094   50  female  33.7         4     no  southwest  11299.34300
1141   41  female  32.6         3     no  southwest   7954.51700
1144   50    male  32.3         2     no  southwest   9630.39700
1171   43  female  26.7         2    yes  southwest  22478.60000
1207   36    male  33.4         2    yes  southwest  38415.47400
1246   45  female  25.7         3     no  southwest   9101.79800
1253   40  female  29.3         4     no  southwest  15828.82173
1269   45    male  27.5         3     no  southwest   8615.30000
1309   41    male  32.2         2     no  southwest   6875.96100

In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv(r"C:\Users\Admin\Desktop\projects\Data Science-1pm\Pandas\smartphones_cleaned_v6.csv")

In [9]:
df.sample(20)

,brand_name,model,price,rating,has_5g,has_nfc,has_ir_blaster,processor_brand,num_cores,processor_speed,...,refresh_rate,num_rear_cameras,num_front_cameras,os,primary_camera_rear,primary_camera_front,extended_memory_available,extended_upto,resolution_width,resolution_height
302,xiaomi,Xiaomi Redmi 10 (6GB RAM + 128GB),11999,75.0,False,False,False,snapdragon,8.0,2.40,...,60,2,1.0,android,50.0,5.0,1,512.0,720,1600
130,xiaomi,Xiaomi Redmi 11 Prime 5G,13466,74.0,True,False,True,dimensity,8.0,2.20,...,90,2,1.0,android,50.0,5.0,1,512.0,1080,2408
521,apple,Apple iPhone 13 Pro (256GB),129900,83.0,True,True,False,bionic,6.0,3.22,...,120,3,1.0,ios,12.0,12.0,0,NaN,1170,2532
971,oppo,Oppo Find X6,69990,89.0,True,True,False,snapdragon,8.0,3.20,...,120,3,1.0,android,50.0,32.0,0,NaN,1080,2400
208,xiaomi,Xiaomi Redmi Note 12 Pro (8GB RAM + 256GB),27994,82.0,True,False,True,dimensity,8.0,2.60,...,120,3,1.0,android,50.0,16.0,0,NaN,1080,2400
454,iqoo,iQOO 9 SE 5G (12GB RAM + 256GB),34949,85.0,True,True,False,snapdragon,8.0,2.84,...,120,3,1.0,android,48.0,16.0,0,NaN,1080,2400
430,poco,Poco F5,34990,85.0,True,True,False,snapdragon,8.0,3.20,...,120,3,1.0,android,64.0,32.0,0,NaN,1080,2400
490,samsung,Samsung Galaxy A15,15990,63.0,False,False,False,NaN,8.0,NaN,...,60,3,1.0,android,48.0,8.0,1,1024.0,720,1600
434,xiaomi,Xiaomi Redmi Note 11S (8GB RAM + 128GB),15824,84.0,False,False,True,helio,8.0,2.05,...,90,4,1.0,android,108.0,16.0,1,512.0,1080,2400
235,xiaomi,Xiaomi Mix Fold 2 5G,106990,NaN,True,True,True,snapdragon,8.0,3.20,...,120,3,1.0,android,50.0,20.0,0,NaN,1914,2160
782,vivo,Vivo Y53t,11999,67.0,True,False,False,dimensity,8.0,2.00,...,60,2,1.0,android,13.0,5.0,0,NaN,720,1600
337,oneplus,OnePlus 9 Pro,64800,89.0,True,True,False,snapdragon,8.0,2.84,...,120,4,1.0,android,48.0,16.0,0,NaN,1440,3216
330,iqoo,iQOO Z6 Pro 5G (8GB RAM + 128GB),23399,80.0,True,False,False,snapdragon,8.0,2.40,...,90,3,1.0,android,64.0,16.0,0,NaN,1080,2404
402,xiaomi,Xiaomi Redmi Note 11T 5G,16999,79.0,True,False,True,dimensity,8.0,2.40,...,90,2,1.0,android,50.0,16.0,1,1024.0,1080,2400
486,vivo,Vivo T1x (4GB RAM + 128GB),12999,75.0,False,False,False,snapdragon,8.0,2.40,...,90,2,1.0,android,50.0,8.0,1,NaN,1080,2408
977,poco,POCO X4 GT 5G (8GB RAM + 256GB),28990,85.0,True,True,True,dimensity,8.0,2.85,...,144,3,1.0,android,64.0,16.0,0,NaN,1080,2460
802,poco,Poco X6 Pro 5G,19999,72.0,True,False,False,snapdragon,8.0,NaN,...,120,4,1.0,android,64.0,32.0,1,1024.0,1080,2400
642,oppo,OPPO Reno 9 Z,22990,84.0,True,True,False,snapdragon,8.0,2.20,...,120,3,1.0,android,50.0,32.0,1,NaN,1080,2400
380,letv,Letv Y2 Pro,6999,NaN,False,False,False,unisoc,8.0,NaN,...,60,3,1.0,android,13.0,8.0,0,NaN,720,1560
438,xiaomi,Xiaomi Redmi 9A,6999,61.0,False,False,False,helio,8.0,2.00,...,60,1,1.0,android,13.0,5.0,1,512.0,720,1600

In [5]:
df.shape

(980, 26)

In [8]:
# find the total number of unique brands
df['brand_name'].unique().shape[0]

46

In [12]:
# find the avg price of each brands

grp_brand = df.groupby("brand_name")

In [15]:
grp_brand.get_group("oneplus")

,brand_name,model,price,rating,has_5g,has_nfc,has_ir_blaster,processor_brand,num_cores,processor_speed,...,refresh_rate,num_rear_cameras,num_front_cameras,os,primary_camera_rear,primary_camera_front,extended_memory_available,extended_upto,resolution_width,resolution_height
0,oneplus,OnePlus 11 5G,54999,89.0,True,True,False,snapdragon,8.0,3.20,...,120,3,1.0,android,50.0,16.0,0,NaN,1440,3216
1,oneplus,OnePlus Nord CE 2 Lite 5G,19989,81.0,True,False,False,snapdragon,8.0,2.20,...,120,3,1.0,android,64.0,16.0,1,1024.0,1080,2412
9,oneplus,OnePlus Nord 2T 5G,28999,84.0,True,True,False,dimensity,8.0,3.00,...,90,3,1.0,android,50.0,32.0,0,NaN,1080,2400
18,oneplus,OnePlus 10R 5G,32999,86.0,True,True,False,dimensity,8.0,2.85,...,120,3,1.0,android,50.0,16.0,0,NaN,1080,2412
20,oneplus,OnePlus 11R,39999,85.0,True,True,False,snapdragon,8.0,3.20,...,120,3,1.0,android,50.0,16.0,0,NaN,1080,2412
26,oneplus,OnePlus Nord CE 2 Lite 5G (8GB RAM + 128GB),21995,84.0,True,False,False,snapdragon,8.0,2.20,...,120,3,1.0,android,64.0,16.0,1,1024.0,1080,2412
29,oneplus,OnePlus 11 Pro,69999,NaN,True,True,False,snapdragon,8.0,3.20,...,120,3,1.0,android,50.0,16.0,0,NaN,1440,3216
40,oneplus,OnePlus Nord CE 3 5G,21999,83.0,True,True,False,snapdragon,8.0,2.20,...,120,3,1.0,android,108.0,16.0,1,1024.0,1080,2412
66,oneplus,OnePlus 10 Pro 5G,60999,89.0,True,True,False,snapdragon,8.0,3.00,...,120,3,1.0,android,50.0,32.0,0,NaN,1440,3216
73,oneplus,OnePlus 10T,44999,85.0,True,True,False,snapdragon,8.0,3.20,...,120,3,1.0,android,50.0,16.0,0,NaN,1080,2412
91,oneplus,OnePlus Ace Racing Edition 5G,22990,83.0,True,True,False,dimensity,8.0,2.85,...,120,3,1.0,android,64.0,16.0,0,NaN,1080,2412
109,oneplus,OnePlus 10R 5G (12GB RAM + 256GB),36999,87.0,True,True,False,dimensity,8.0,2.85,...,120,3,1.0,android,50.0,16.0,0,NaN,1080,2412
121,oneplus,OnePlus Nord 2T (12GB RAM + 256GB),33900,85.0,True,True,False,dimensity,8.0,3.00,...,90,3,1.0,android,50.0,32.0,0,NaN,1080,2400
127,oneplus,OnePlus Nord CE 2 Lite 5G (8GB RAM + 256GB),24999,85.0,True,False,False,snapdragon,8.0,2.20,...,120,3,1.0,android,64.0,16.0,1,1024.0,1080,2412
144,oneplus,OnePlus Clover,14999,69.0,False,False,False,snapdragon,8.0,1.80,...,60,3,1.0,android,13.0,8.0,1,NaN,720,1560
185,oneplus,OnePlus Nord 3 5G,27999,84.0,True,True,False,dimensity,8.0,3.10,...,90,3,1.0,android,50.0,32.0,0,NaN,1080,2400
196,oneplus,OnePlus Nord CE 3 Lite 5G,18999,81.0,True,False,False,snapdragon,8.0,2.20,...,120,3,1.0,android,50.0,16.0,1,1024.0,1080,2412
229,oneplus,OnePlus 10 Pro 5G (12GB RAM + 256GB),65499,NaN,True,True,False,snapdragon,8.0,3.00,...,120,3,1.0,android,50.0,32.0,0,NaN,1440,3216
266,oneplus,OnePlus Ace 2,34999,84.0,True,True,False,snapdragon,8.0,3.20,...,120,3,1.0,android,50.0,16.0,0,NaN,1080,2412
306,oneplus,OnePlus 10T (16GB RAM + 256GB),55999,87.0,True,True,False,snapdragon,8.0,3.20,...,120,3,1.0,android,50.0,16.0,0,NaN,1080,2412
309,oneplus,OnePlus 9RT 5G,42999,85.0,True,True,False,snapdragon,8.0,2.84,...,120,3,1.0,android,50.0,16.0,0,NaN,1080,2400
337,oneplus,OnePlus 9 Pro,64800,89.0,True,True,False,snapdragon,8.0,2.84,...,120,4,1.0,android,48.0,16.0,0,NaN,1440,3216
343,oneplus,OnePlus Nord N20 5G,20990,81.0,True,True,False,snapdragon,8.0,2.20,...,60,3,1.0,android,64.0,16.0,1,NaN,1080,2400
364,oneplus,OnePlus 10T (12GB RAM + 256GB),50999,87.0,True,True,False,snapdragon,8.0,3.20,...,120,3,1.0,android,50.0,16.0,0,NaN,1080,2412
410,oneplus,OnePlus Nord N200,16990,75.0,True,True,False,snapdragon,8.0,2.00,...,90,3,1.0,android,13.0,16.0,1,NaN,1080,2400
421,oneplus,OnePlus 10 Pro 5G (12GB RAM + 512GB),74999,NaN,True,True,False,snapdragon,8.0,3.00,...,120,3,1.0,android,50.0,32.0,0,NaN,1440,3216
499,oneplus,OnePlus 6 (8GB RAM + 128GB),27999,77.0,False,True,False,snapdragon,8.0,2.80,...,60,2,1.0,android,20.0,16.0,0,NaN,1080,2280
510,oneplus,OnePlus 12 Pro,69999,NaN,True,True,False,snapdragon,8.0,3.20,...,144,3,1.0,android,108.0,32.0,0,NaN,1440,3412
526,oneplus,OnePlus 10R Prime Edition,35389,85.0,True,True,False,dimensity,8.0,2.85,...,120,3,1.0,android,50.0,16.0,0,NaN,1080,2412
550,oneplus,OnePlus Nord 3T 5G,29990,84.0,True,True,False,dimensity,8.0,3.00,...,90,3,1.0,android,50.0,32.0,0,NaN,1080,2400
592,oneplus,OnePlus Nord Lite,19999,77.0,False,False,False,snapdragon,8.0,2.00,...,90,3,1.0,android,48.0,16.0,0,NaN,1080,2400
624,oneplus,OnePlus Nord 2 Lite 5G,22999,83.0,True,True,False,snapdragon,8.0,2.20,...,120,3,1.0,android,64.0,16.0,1,NaN,1080,2412
640,oneplus,OnePlus Nord 5,34999,76.0,True,True,False,dimensity,8.0,NaN,...,120,3,1.0,android,64.0,32.0,0,NaN,1080,2400
688,oneplus,OnePlus Nord N10,25595,81.0,True,True,False,snapdragon,8.0,2.00,...,90,4,1.0,android,64.0,16.0,1,512.0,1080,2400
793,oneplus,OnePlus Nord N300,18990,75.0,True,True,False,dimensity,8.0,2.40,...,90,2,1.0,android,48.0,16.0,1,NaN,720,1612
855,oneplus,OnePlus Nord 4 5G,29999,83.0,True,True,False,snapdragon,8.0,2.36,...,120,3,1.0,android,50.0,32.0,0,NaN,1080,2412
857,oneplus,OnePlus Ace 5G,28990,84.0,True,True,False,dimensity,8.0,2.85,...,120,3,1.0,android,50.0,16.0,0,NaN,1080,2412
871,oneplus,OnePlus 9T,44999,86.0,True,True,False,snapdragon,8.0,2.84,...,120,4,1.0,android,108.0,16.0,0,NaN,1080,2400
877,oneplus,OnePlus Nord SE,19999,73.0,False,False,False,snapdragon,8.0,2.00,...,60,4,1.0,android,48.0,13.0,1,256.0,1080,2400
879,oneplus,OnePlus Nord N100,16990,68.0,False,False,False,snapdragon,8.0,1.80,...,90,3,1.0,android,13.0,8.0,1,256.0,720,1600
908,oneplus,OnePlus Ace Pro,47990,86.0,True,True,False,snapdragon,8.0,3.20,...,120,3,1.0,android,50.0,16.0,0,NaN,1080,2412
949,oneplus,OnePlus Z,24999,79.0,False,False,False,snapdragon,8.0,2.40,...,90,3,1.0,android,64.0,16.0,0,NaN,1080,2400

In [19]:
grp_brand['price'].mean()

brand_name
apple         95966.521739
asus          74709.428571
blackview      8990.000000
blu           14990.000000
cat           14999.000000
cola          14999.000000
doogee        30499.000000
duoqin         9990.000000
gionee         6896.000000
google        44332.571429
honor         30301.846154
huawei        80177.250000
ikall          7632.333333
infinix       14664.793103
iqoo          30301.875000
itel           5811.000000
jio            7159.250000
lava          11246.750000
leeco         10999.000000
leitz        124990.000000
lenovo        53494.500000
letv           6165.666667
lg            63329.333333
lyf            3940.000000
micromax       6929.333333
motorola      24099.923077
nokia         24630.769231
nothing       31195.400000
nubia         49827.833333
oneplus       35858.571429
oppo          29650.034091
oukitel       26293.000000
poco          18479.195122
realme        17461.422680
redmi         15665.666667
royole       129999.000000
samsung       36843.030303
sharp         59990.000000
sony          60570.666667
tcl            8990.000000
tecno         14545.363636
tesla         69999.000000
vertu        650000.000000
vivo          26782.387387
xiaomi        27961.111940
zte           40994.500000
Name: price, dtype: float64

In [20]:
# top 10 costliest phone brand

In [25]:
df.groupby('brand_name')['price'].mean().sort_values(ascending=False)[:10]

brand_name
vertu     650000.000000
royole    129999.000000
leitz     124990.000000
apple      95966.521739
huawei     80177.250000
asus       74709.428571
tesla      69999.000000
lg         63329.333333
sony       60570.666667
sharp      59990.000000
Name: price, dtype: float64

In [27]:
df

,brand_name,model,price,rating,has_5g,has_nfc,has_ir_blaster,processor_brand,num_cores,processor_speed,...,refresh_rate,num_rear_cameras,num_front_cameras,os,primary_camera_rear,primary_camera_front,extended_memory_available,extended_upto,resolution_width,resolution_height
0,oneplus,OnePlus 11 5G,54999,89.0,True,True,False,snapdragon,8.0,3.20,...,120,3,1.0,android,50.0,16.0,0,NaN,1440,3216
1,oneplus,OnePlus Nord CE 2 Lite 5G,19989,81.0,True,False,False,snapdragon,8.0,2.20,...,120,3,1.0,android,64.0,16.0,1,1024.0,1080,2412
2,samsung,Samsung Galaxy A14 5G,16499,75.0,True,False,False,exynos,8.0,2.40,...,90,3,1.0,android,50.0,13.0,1,1024.0,1080,2408
3,motorola,Motorola Moto G62 5G,14999,81.0,True,False,False,snapdragon,8.0,2.20,...,120,3,1.0,android,50.0,16.0,1,1024.0,1080,2400
4,realme,Realme 10 Pro Plus,24999,82.0,True,False,False,dimensity,8.0,2.60,...,120,3,1.0,android,108.0,16.0,0,NaN,1080,2412
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
975,motorola,Motorola Moto Edge S30 Pro,34990,83.0,True,False,False,snapdragon,8.0,3.00,...,120,3,1.0,android,64.0,16.0,0,NaN,1080,2460
976,honor,Honor X8 5G,14990,75.0,True,False,False,snapdragon,8.0,2.20,...,60,3,1.0,android,48.0,8.0,1,1024.0,720,1600
977,poco,POCO X4 GT 5G (8GB RAM + 256GB),28990,85.0,True,True,True,dimensity,8.0,2.85,...,144,3,1.0,android,64.0,16.0,0,NaN,1080,2460
978,motorola,Motorola Moto G91 5G,19990,80.0,True,True,False,snapdragon,8.0,2.20,...,60,3,1.0,android,108.0,32.0,1,1024.0,1080,2400
979,samsung,Samsung Galaxy M52s 5G,24990,74.0,True,False,False,NaN,8.0,NaN,...,60,3,1.0,android,64.0,32.0,1,1024.0,1080,2400

In [30]:
# find the highest avg rated phone
df.groupby('brand_name')['rating'].mean().sort_values(ascending=False)[:1]/10

brand_name
leitz    8.9
Name: rating, dtype: float64

In [31]:
# count the number of brands which are providing different types of processor

In [40]:
df.groupby(['processor_brand', 'brand_name', 'has_5g'])['brand_name'].count()

processor_brand  brand_name  has_5g
bionic           apple       False      8
                             True      37
dimensity        asus        True       2
                 blu         True       1
                 doogee      True       1
                                       ..
unisoc           micromax    False      2
                 nokia       False      6
                 realme      False      7
                 samsung     False      3
                 tecno       False      2
Name: brand_name, Length: 107, dtype: int64

In [38]:
df

,brand_name,model,price,rating,has_5g,has_nfc,has_ir_blaster,processor_brand,num_cores,processor_speed,...,refresh_rate,num_rear_cameras,num_front_cameras,os,primary_camera_rear,primary_camera_front,extended_memory_available,extended_upto,resolution_width,resolution_height
0,oneplus,OnePlus 11 5G,54999,89.0,True,True,False,snapdragon,8.0,3.20,...,120,3,1.0,android,50.0,16.0,0,NaN,1440,3216
1,oneplus,OnePlus Nord CE 2 Lite 5G,19989,81.0,True,False,False,snapdragon,8.0,2.20,...,120,3,1.0,android,64.0,16.0,1,1024.0,1080,2412
2,samsung,Samsung Galaxy A14 5G,16499,75.0,True,False,False,exynos,8.0,2.40,...,90,3,1.0,android,50.0,13.0,1,1024.0,1080,2408
3,motorola,Motorola Moto G62 5G,14999,81.0,True,False,False,snapdragon,8.0,2.20,...,120,3,1.0,android,50.0,16.0,1,1024.0,1080,2400
4,realme,Realme 10 Pro Plus,24999,82.0,True,False,False,dimensity,8.0,2.60,...,120,3,1.0,android,108.0,16.0,0,NaN,1080,2412
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
975,motorola,Motorola Moto Edge S30 Pro,34990,83.0,True,False,False,snapdragon,8.0,3.00,...,120,3,1.0,android,64.0,16.0,0,NaN,1080,2460
976,honor,Honor X8 5G,14990,75.0,True,False,False,snapdragon,8.0,2.20,...,60,3,1.0,android,48.0,8.0,1,1024.0,720,1600
977,poco,POCO X4 GT 5G (8GB RAM + 256GB),28990,85.0,True,True,True,dimensity,8.0,2.85,...,144,3,1.0,android,64.0,16.0,0,NaN,1080,2460
978,motorola,Motorola Moto G91 5G,19990,80.0,True,True,False,snapdragon,8.0,2.20,...,60,3,1.0,android,108.0,32.0,1,1024.0,1080,2400
979,samsung,Samsung Galaxy M52s 5G,24990,74.0,True,False,False,NaN,8.0,NaN,...,60,3,1.0,android,64.0,32.0,1,1024.0,1080,2400

In [39]:
# find the brand having fastest processor speed

In [43]:
np.round(df.groupby('brand_name')['processor_speed'].mean().sort_values(ascending = False)[:1], 2)

brand_name
asus    3.16
Name: processor_speed, dtype: float64

In [45]:
df['processor_brand'].value_counts()

processor_brand
snapdragon    413
helio         201
dimensity     177
exynos         50
bionic         45
unisoc         26
tiger          24
google          9
kirin           7
spreadtrum      4
sc9863a         2
fusion          1
mediatek        1
Name: count, dtype: int64

In [47]:
df.groupby('processor_brand')['processor_brand'].count()

processor_brand
bionic         45
dimensity     177
exynos         50
fusion          1
google          9
helio         201
kirin           7
mediatek        1
sc9863a         2
snapdragon    413
spreadtrum      4
tiger          24
unisoc         26
Name: processor_brand, dtype: int64

In [51]:
grp_brand.get_group('apple').describe()

,price,rating,num_cores,processor_speed,battery_capacity,fast_charging_available,fast_charging,ram_capacity,internal_memory,screen_size,refresh_rate,num_rear_cameras,num_front_cameras,primary_camera_rear,primary_camera_front,extended_memory_available,extended_upto,resolution_width,resolution_height
count,46.000000,44.000000,41.000000,32.000000,35.000000,46.000000,3.000000,46.000000,46.000000,46.000000,46.000000,46.000000,46.0,46.00000,46.000000,46.0,0.0,46.000000,46.000000
mean,95966.521739,76.795455,6.000000,3.074375,3527.228571,0.695652,20.333333,5.282609,263.652174,6.079565,82.173913,2.304348,1.0,20.76087,11.452174,0.0,NaN,1127.282609,2414.434783
std,43386.618947,6.249017,0.447214,0.239865,756.376621,0.465215,4.041452,1.360768,271.963169,0.579498,29.281245,0.662305,0.0,15.75533,1.589093,0.0,NaN,174.537314,439.624064
min,29990.000000,60.000000,4.000000,2.370000,1821.000000,0.000000,18.000000,3.000000,32.000000,4.700000,60.000000,1.000000,1.0,12.00000,7.000000,0.0,NaN,750.000000,1334.000000
25%,57749.000000,75.000000,6.000000,3.100000,3110.000000,0.000000,18.000000,4.000000,128.000000,6.100000,60.000000,2.000000,1.0,12.00000,12.000000,0.0,NaN,1080.000000,2340.000000
50%,84994.500000,77.500000,6.000000,3.220000,3279.000000,1.000000,18.000000,6.000000,128.000000,6.100000,60.000000,2.000000,1.0,12.00000,12.000000,0.0,NaN,1170.000000,2532.000000
75%,129990.000000,81.250000,6.000000,3.220000,4324.000000,1.000000,21.500000,6.000000,256.000000,6.695000,120.000000,3.000000,1.0,12.75000,12.000000,0.0,NaN,1284.000000,2778.000000
max,182999.000000,86.000000,8.000000,3.220000,4700.000000,1.000000,25.000000,8.000000,1024.000000,6.730000,120.000000,3.000000,1.0,50.00000,13.000000,0.0,NaN,1290.000000,2796.000000

In [ ]:
grp_brand.get_group('apple').agg()

,brand_name,model,price,rating,has_5g,has_nfc,has_ir_blaster,processor_brand,num_cores,processor_speed,...,refresh_rate,num_rear_cameras,num_front_cameras,os,primary_camera_rear,primary_camera_front,extended_memory_available,extended_upto,resolution_width,resolution_height
6,apple,Apple iPhone 14,65999,81.0,True,True,False,bionic,6.0,3.22,...,60,2,1.0,ios,12.0,12.0,0,NaN,1170,2532
15,apple,Apple iPhone 13,62999,79.0,True,True,False,bionic,6.0,3.22,...,60,2,1.0,ios,12.0,12.0,0,NaN,1170,2532
27,apple,Apple iPhone 14 Pro Max,129990,76.0,True,True,False,bionic,6.0,NaN,...,120,3,1.0,ios,48.0,12.0,0,NaN,1290,2796
33,apple,Apple iPhone 11,38999,73.0,False,True,False,bionic,6.0,2.65,...,60,2,1.0,ios,12.0,12.0,0,NaN,828,1792
56,apple,Apple iPhone 14 Plus,74999,82.0,True,True,False,bionic,6.0,3.22,...,60,2,1.0,ios,12.0,12.0,0,NaN,1284,2778
76,apple,Apple iPhone 13 Pro,119900,83.0,True,True,False,bionic,6.0,3.22,...,120,3,1.0,ios,12.0,12.0,0,NaN,1170,2532
100,apple,Apple iPhone 14 Pro,119990,75.0,True,True,False,bionic,6.0,NaN,...,120,3,1.0,ios,48.0,12.0,0,NaN,1179,2556
111,apple,Apple iPhone 12,51999,74.0,True,True,False,bionic,6.0,3.10,...,60,2,1.0,ios,12.0,12.0,0,NaN,1170,2532
136,apple,Apple iPhone 11 (128GB),46999,75.0,False,True,False,bionic,6.0,2.65,...,60,2,1.0,ios,12.0,12.0,0,NaN,828,1792
149,apple,Apple iPhone 12 Mini,40999,74.0,True,True,False,bionic,6.0,3.10,...,60,2,1.0,ios,12.0,12.0,0,NaN,1080,2340
152,apple,Apple iPhone 15 Pro Max,142990,79.0,True,True,False,bionic,NaN,NaN,...,120,3,1.0,ios,50.0,12.0,0,NaN,1284,2778
161,apple,Apple iPhone 13 Pro Max,129900,84.0,True,True,False,bionic,6.0,3.22,...,120,3,1.0,ios,12.0,12.0,0,NaN,1284,2778
173,apple,Apple iPhone 9,29990,61.0,False,True,False,bionic,6.0,2.65,...,60,1,1.0,ios,12.0,7.0,0,NaN,750,1334
209,apple,Apple iPhone 14 Pro Max (256GB),139990,77.0,True,True,False,bionic,6.0,NaN,...,120,3,1.0,ios,48.0,12.0,0,NaN,1290,2796
246,apple,Apple iPhone 14 (256GB),75999,82.0,True,True,False,bionic,6.0,3.22,...,60,2,1.0,ios,12.0,12.0,0,NaN,1170,2532
262,apple,Apple iPhone XR2,71999,60.0,False,True,False,bionic,NaN,NaN,...,60,2,1.0,ios,12.0,7.0,0,NaN,828,1792
275,apple,Apple iPhone 13 Mini,64900,79.0,True,True,False,bionic,6.0,3.22,...,60,2,1.0,ios,12.0,12.0,0,NaN,1080,2340
280,apple,Apple iPhone 14 Mini,69990,70.0,False,True,False,bionic,NaN,NaN,...,60,2,1.0,ios,12.0,12.0,0,NaN,1080,2340
288,apple,Apple iPhone 14 Pro Max (1TB),182999,78.0,True,True,False,bionic,6.0,NaN,...,120,3,1.0,ios,48.0,12.0,0,NaN,1290,2796
305,apple,Apple iPhone 12 (128GB),55999,75.0,True,True,False,bionic,6.0,3.10,...,60,2,1.0,ios,12.0,12.0,0,NaN,1170,2532
321,apple,Apple iPhone 14 Plus (256GB),84999,83.0,True,True,False,bionic,6.0,3.22,...,60,2,1.0,ios,12.0,12.0,0,NaN,1284,2778
344,apple,Apple iPhone 13 (256GB),72999,79.0,True,True,False,bionic,6.0,3.22,...,60,2,1.0,ios,12.0,12.0,0,NaN,1170,2532
361,apple,Apple iPhone 12 Mini (128GB),45999,75.0,True,True,False,bionic,6.0,3.10,...,60,2,1.0,ios,12.0,12.0,0,NaN,1080,2340
398,apple,Apple iPhone 15 Ultra,149900,79.0,True,True,False,bionic,8.0,NaN,...,120,3,1.0,ios,48.0,12.0,0,NaN,1290,2796
416,apple,Apple iPhone 14 Pro (256GB),129990,76.0,True,True,False,bionic,6.0,NaN,...,120,3,1.0,ios,48.0,12.0,0,NaN,1179,2556
435,apple,Apple iPhone SE 3 2022,43900,NaN,True,True,False,bionic,6.0,3.22,...,60,1,1.0,ios,12.0,7.0,0,NaN,750,1334
444,apple,Apple iPhone 15 Pro,130990,75.0,True,True,False,bionic,NaN,NaN,...,120,3,1.0,ios,50.0,12.0,0,NaN,1170,2532
521,apple,Apple iPhone 13 Pro (256GB),129900,83.0,True,True,False,bionic,6.0,3.22,...,120,3,1.0,ios,12.0,12.0,0,NaN,1170,2532
594,apple,Apple iPhone 11 Pro Max,109900,77.0,False,True,False,bionic,6.0,2.65,...,60,3,1.0,ios,12.0,12.0,0,NaN,1242,2688
595,apple,Apple iPhone 7s,52990,NaN,False,False,False,fusion,4.0,2.37,...,60,1,1.0,ios,13.0,7.0,0,NaN,750,1334
613,apple,Apple iPhone 12 Pro (512GB),139900,80.0,True,True,False,bionic,6.0,3.10,...,60,3,1.0,ios,12.0,12.0,0,NaN,1170,2532
621,apple,Apple iPhone 14 (512GB),95999,82.0,True,True,False,bionic,6.0,3.22,...,60,2,1.0,ios,12.0,12.0,0,NaN,1170,2532
638,apple,Apple iPhone SE 2020,39900,63.0,False,True,False,bionic,6.0,2.65,...,60,1,1.0,ios,12.0,7.0,0,NaN,750,1334
682,apple,Apple iPhone 13 Pro Max (256GB),139900,84.0,True,True,False,bionic,6.0,3.22,...,120,3,1.0,ios,12.0,12.0,0,NaN,1284,2778
706,apple,Apple iPhone 15,82990,72.0,False,True,False,bionic,NaN,NaN,...,60,2,1.0,ios,50.0,13.0,0,NaN,1170,2532
737,apple,Apple iPhone SE 4,49990,60.0,True,True,False,bionic,6.0,3.22,...,60,1,1.0,ios,12.0,10.8,0,NaN,750,1580
739,apple,Apple iPhone 14 Pro Max (512GB),169900,78.0,True,True,False,bionic,6.0,NaN,...,120,3,1.0,ios,48.0,12.0,0,NaN,1290,2796
756,apple,Apple iPhone 13 Pro Max (1TB),179900,86.0,True,True,False,bionic,6.0,3.22,...,120,3,1.0,ios,12.0,12.0,0,NaN,1284,2778
788,apple,Apple iPhone 14 Plus (512GB),104999,83.0,True,True,False,bionic,6.0,3.22,...,60,2,1.0,ios,12.0,12.0,0,NaN,1284,2778
789,apple,Apple iPhone 14 Pro (1TB),172999,77.0,True,True,False,bionic,6.0,NaN,...,120,3,1.0,ios,48.0,12.0,0,NaN,1179,2556
813,apple,Apple iPhone 13 (512GB),91999,80.0,True,True,False,bionic,6.0,3.22,...,60,2,1.0,ios,12.0,12.0,0,NaN,1170,2532
824,apple,Apple iPhone 12 Pro (256GB),119900,80.0,True,True,False,bionic,6.0,3.10,...,60,3,1.0,ios,12.0,12.0,0,NaN,1170,2532
880,apple,Apple iPhone 12 Mini (256GB),55999,75.0,True,True,False,bionic,6.0,3.10,...,60,2,1.0,ios,12.0,12.0,0,NaN,1080,2340
881,apple,Apple iPhone 12 (256GB),67999,76.0,True,True,False,bionic,6.0,3.10,...,60,2,1.0,ios,12.0,12.0,0,NaN,1170,2532
892,apple,Apple iPhone 15 Plus,84990,75.0,True,True,False,bionic,6.0,NaN,...,120,2,1.0,ios,12.0,12.0,0,NaN,1284,2778
923,apple,Apple iPhone 13 Pro (1TB),147900,84.0,True,True,False,bionic,6.0,3.22,...,120,3,1.0,ios,12.0,12.0,0,NaN,1170,2532

In [60]:
df.groupby(['brand_name', 'processor_brand']).get_group(('iqoo', 'dimensity'))

,brand_name,model,price,rating,has_5g,has_nfc,has_ir_blaster,processor_brand,num_cores,processor_speed,...,refresh_rate,num_rear_cameras,num_front_cameras,os,primary_camera_rear,primary_camera_front,extended_memory_available,extended_upto,resolution_width,resolution_height
51,iqoo,iQOO Neo 7 5G,29999,82.0,True,True,True,dimensity,8.0,3.1,...,120,3,1.0,android,64.0,16.0,0,NaN,1080,2400
282,iqoo,iQOO Neo 7 SE 5G,24990,83.0,True,True,False,dimensity,8.0,3.1,...,120,3,1.0,android,64.0,16.0,0,NaN,1080,2400

In [61]:
df.head(10)

,brand_name,model,price,rating,has_5g,has_nfc,has_ir_blaster,processor_brand,num_cores,processor_speed,...,refresh_rate,num_rear_cameras,num_front_cameras,os,primary_camera_rear,primary_camera_front,extended_memory_available,extended_upto,resolution_width,resolution_height
0,oneplus,OnePlus 11 5G,54999,89.0,True,True,False,snapdragon,8.0,3.20,...,120,3,1.0,android,50.0,16.0,0,NaN,1440,3216
1,oneplus,OnePlus Nord CE 2 Lite 5G,19989,81.0,True,False,False,snapdragon,8.0,2.20,...,120,3,1.0,android,64.0,16.0,1,1024.0,1080,2412
2,samsung,Samsung Galaxy A14 5G,16499,75.0,True,False,False,exynos,8.0,2.40,...,90,3,1.0,android,50.0,13.0,1,1024.0,1080,2408
3,motorola,Motorola Moto G62 5G,14999,81.0,True,False,False,snapdragon,8.0,2.20,...,120,3,1.0,android,50.0,16.0,1,1024.0,1080,2400
4,realme,Realme 10 Pro Plus,24999,82.0,True,False,False,dimensity,8.0,2.60,...,120,3,1.0,android,108.0,16.0,0,NaN,1080,2412
5,samsung,Samsung Galaxy F23 5G (6GB RAM + 128GB),16999,80.0,True,True,False,snapdragon,8.0,2.20,...,120,3,1.0,android,50.0,8.0,1,1024.0,1080,2408
6,apple,Apple iPhone 14,65999,81.0,True,True,False,bionic,6.0,3.22,...,60,2,1.0,ios,12.0,12.0,0,NaN,1170,2532
7,xiaomi,Xiaomi Redmi Note 12 Pro Plus,29999,86.0,True,False,True,dimensity,8.0,2.60,...,120,3,1.0,android,200.0,16.0,0,NaN,1080,2400
8,nothing,Nothing Phone 1,26749,85.0,True,True,False,snapdragon,8.0,2.50,...,120,2,1.0,android,50.0,16.0,0,NaN,1080,2400
9,oneplus,OnePlus Nord 2T 5G,28999,84.0,True,True,False,dimensity,8.0,3.00,...,90,3,1.0,android,50.0,32.0,0,NaN,1080,2400

In [69]:
grp_brand.agg(
    {'price' : 'mean',
     'processor_brand' : 'count',
     'num_cores' : 'mean'}
).sort_values(by = 'price', ascending = False).reset_index()

   brand_name          price  processor_brand  num_cores
0       vertu  650000.000000                1   8.000000
1      royole  129999.000000                2   8.000000
2       leitz  124990.000000                1   8.000000
3       apple   95966.521739               46   6.000000
4      huawei   80177.250000               15   8.000000
5        asus   74709.428571                7   8.000000
6       tesla   69999.000000                0   8.000000
7          lg   63329.333333                3   8.000000
8        sony   60570.666667                9   8.000000
9       sharp   59990.000000                1   8.000000
10     lenovo   53494.500000                2   8.000000
11      nubia   49827.833333                6   8.000000
12     google   44332.571429               14   8.000000
13        zte   40994.500000                2   8.000000
14    samsung   36843.030303              121   7.939394
15    oneplus   35858.571429               42   8.000000
16    nothing   31195.400000                5   8.000000
17     doogee   30499.000000                2   8.000000
18       iqoo   30301.875000               32   8.000000
19      honor   30301.846154               13   8.000000
20       oppo   29650.034091               88   8.000000
21     xiaomi   27961.111940              134   7.910448
22       vivo   26782.387387              111   7.891892
23    oukitel   26293.000000                3   8.000000
24      nokia   24630.769231               13   8.000000
25   motorola   24099.923077               52   8.000000
26       poco   18479.195122               41   7.804878
27     realme   17461.422680               97   8.000000
28      redmi   15665.666667                3   8.000000
29       cola   14999.000000                1   8.000000
30        cat   14999.000000                1   4.000000
31        blu   14990.000000                1   8.000000
32    infinix   14664.793103               29   7.724138
33      tecno   14545.363636               32   7.636364
34       lava   11246.750000                4   7.000000
35      leeco   10999.000000                1   4.000000
36     duoqin    9990.000000                1   8.000000
37        tcl    8990.000000                1   8.000000
38  blackview    8990.000000                1   8.000000
39      ikall    7632.333333                0   4.000000
40        jio    7159.250000                3   5.000000
41   micromax    6929.333333                3   8.000000
42     gionee    6896.000000                3   5.333333
43       letv    6165.666667                3   5.333333
44       itel    5811.000000                8   5.200000
45        lyf    3940.000000                2   8.000000

In [71]:
grp_brand.agg(['min'])

TypeError: agg function failed [how->min,dtype->object]

In [89]:
df = pd.read_csv(r"C:\Users\Admin\Desktop\projects\Data Science-1pm\Pandas\Order-CSV.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Admin\\Desktop\\projects\\Data Science-1pm\\Pandas\\Order-CSV.csv'

In [92]:
del df

In [94]:
orders = pd.read_csv(r"C:\Users\Admin\Desktop\projects\Data Science-1pm\Pandas\orders.csv")

In [95]:
order_details = pd.read_csv(r"C:\Users\Admin\Desktop\projects\Data Science-1pm\Pandas\order_details.csv")

In [96]:
orders

    order_id  user_id  order_date
0    B-25601        1  01-04-2018
1    B-26011        1  12-02-2019
2    B-26074        1  21-03-2019
3    B-25602        2  01-04-2018
4    B-26012        2  13-02-2019
..       ...      ...         ...
495  B-26007      407  09-02-2019
496  B-26008      408  09-02-2019
497  B-26009      409  10-02-2019
498  B-26010      410  11-02-2019
499  B-26064      464  16-03-2019

[500 rows x 3 columns]

In [97]:
order_details

     order_id  amount  profit  quantity  category_id
0     B-25601  1275.0 -1148.0         7            1
1     B-25614   494.0    54.0         4            1
2     B-25618   362.0   127.0         1            1
3     B-25638   182.0   -11.0         3            1
4     B-25643  1061.0   -36.0         8            1
...       ...     ...     ...       ...          ...
1495  B-26053    17.0     1.0         2           65
1496  B-26053    27.0     6.0         3           65
1497  B-26078    17.0     8.0         2           65
1498  B-26098    46.0    14.0         5           65
1499  B-26099     9.0     3.0         1           65

[1500 rows x 5 columns]

In [99]:
df = pd.merge(orders, order_details, on = 'order_id')

In [101]:
df.head(10
        )

  order_id  user_id  order_date  amount  profit  quantity  category_id
0  B-25601        1  01-04-2018  1275.0 -1148.0         7            1
1  B-25601        1  01-04-2018    66.0   -12.0         5            2
2  B-25601        1  01-04-2018     8.0    -2.0         3            3
3  B-25601        1  01-04-2018    80.0   -56.0         4            4
4  B-26011        1  12-02-2019    93.0    44.0         2            2
5  B-26074        1  21-03-2019    57.0    21.0         4           22
6  B-25602        2  01-04-2018   168.0  -111.0         2            5
7  B-25602        2  01-04-2018   424.0  -272.0         5            5
8  B-25602        2  01-04-2018  2617.0  1151.0         4            5
9  B-25602        2  01-04-2018   561.0   212.0         3            8

In [102]:
# find the top 10 consistent customer

In [104]:
df.user_id.value_counts()

user_id
51     16
20     14
3      14
43     14
23     13
       ..
260     1
111     1
263     1
265     1
205     1
Name: count, Length: 401, dtype: int64

In [111]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   order_id     1500 non-null   object
 1   user_id      1500 non-null   int64
 2   order_date   1500 non-null   object
 3   amount       1500 non-null   float64
 4   profit       1500 non-null   float64
 5   quantity     1500 non-null   int64
 6   category_id  1500 non-null   float64
dtypes: float64(3), int64(2), object(2)
memory usage: 82.2+ KB

In [110]:
df['category_id'] = df['category_id'].astype(float)

In [112]:
df

     order_id  user_id  order_date  amount  profit  quantity  category_id
0     B-25601        1  01-04-2018  1275.0 -1148.0         7          1.0
1     B-25601        1  01-04-2018    66.0   -12.0         5          2.0
2     B-25601        1  01-04-2018     8.0    -2.0         3          3.0
3     B-25601        1  01-04-2018    80.0   -56.0         4          4.0
4     B-26011        1  12-02-2019    93.0    44.0         2          2.0
...       ...      ...         ...     ...     ...       ...          ...
1495  B-26010      410  11-02-2019   176.0   -13.0         5         34.0
1496  B-26064      464  16-03-2019    61.0     3.0         4          3.0
1497  B-26064      464  16-03-2019    22.0     0.0         2          8.0
1498  B-26064      464  16-03-2019   122.0    38.0         6         18.0
1499  B-26064      464  16-03-2019    75.0     2.0         5         22.0

[1500 rows x 7 columns]

In [ ]:
# Find the avg profit generated in each year
# find the profit in each month of each year

df['order_date'][0].split("-")[-1]

'2018'

In [1]:
pip install seaborn

Collecting seabornNote: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution ~andas (c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~andas (c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~andas (c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages)

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

  Using cached seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from seaborn) (1.26.2)
Requirement already satisfied: pandas>=1.2 in c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from seaborn) (2.2.1)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from seaborn) (3.8.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.2.0)
Requirement already satisfied: cycler>=0.10 in c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.48.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.5)
Requirement already satisfied: packaging>=20.0 in c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (23.2)
Requirement already satisfied: pillow>=8 in c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (10.2.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.1.1)
Requirement already satisfied: python-dateutil>=2.7 in c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from pandas>=1.2->seaborn) (2023.4)
Requirement already satisfied: tzdata>=2022.7 in c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from pandas>=1.2->seaborn) (2023.4)
Requirement already satisfied: six>=1.5 in c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.16.0)
Using cached seaborn-0.13.2-py3-none-any.whl (294 kB)
Installing collected packages: seaborn
Successfully installed seaborn-0.13.2

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns

In [3]:
df = sns.load_dataset("tips")

In [4]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [5]:
df['total_bill'].mean()

19.78594262295082

In [7]:
df.groupby(['sex', "smoker"])['total_bill'].mean()

C:\Users\Admin\AppData\Local\Temp\ipykernel_18388\3817157689.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(['sex', "smoker"])['total_bill'].mean()

sex     smoker
Male    Yes       22.284500
        No        19.791237
Female  Yes       17.977879
        No        18.105185
Name: total_bill, dtype: float64

In [11]:
df.groupby('day')[['total_bill', 'tip']].mean()

C:\Users\Admin\AppData\Local\Temp\ipykernel_18388\3805241267.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('day')[['total_bill', 'tip']].mean()

      total_bill       tip
day
Thur   17.682742  2.771452
Fri    17.151579  2.734737
Sat    20.441379  2.993103
Sun    21.410000  3.255132

In [ ]:
# Pivot Table  : takes simple column wise data as input , and groups the entries into a two dimensional table that provides a multi-dim summarization of the data

In [16]:
df.groupby(['sex', 'smoker'])[['total_bill', 'tip']].mean().unstack()

C:\Users\Admin\AppData\Local\Temp\ipykernel_18388\3969583324.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(['sex', 'smoker'])[['total_bill', 'tip']].mean().unstack()

       total_bill                  tip
smoker        Yes         No       Yes        No
sex
Male    22.284500  19.791237  3.051167  3.113402
Female  17.977879  18.105185  2.931515  2.773519

In [ ]:
df.pivot_table(index = 'sex', columns = 'smoker', values = 'total_bill')

C:\Users\Admin\AppData\Local\Temp\ipykernel_18388\2453703127.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df.pivot_table(index = 'sex', columns = 'smoker', values = 'total_bill')

smoker        Yes         No
sex
Male    22.284500  19.791237
Female  17.977879  18.105185

In [22]:
df.pivot_table(index = 'sex', columns = 'smoker', values = 'total_bill', aggfunc = 'sum')

C:\Users\Admin\AppData\Local\Temp\ipykernel_18388\1100878217.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df.pivot_table(index = 'sex', columns = 'smoker', values = 'total_bill', aggfunc = 'sum')

smoker      Yes       No
sex
Male    1337.07  1919.75
Female   593.27   977.68

In [23]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
df.pivot_table(index = ['sex', 'smoker'], columns = ['day', 'time'], values = 'total_bill', aggfunc='median')

C:\Users\Admin\AppData\Local\Temp\ipykernel_18388\1333563214.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df.pivot_table(index = ['sex', 'smoker'], columns = ['day', 'time'], values = 'total_bill', aggfunc='median')

day              Thur           Fri            Sat    Sun
time            Lunch Dinner  Lunch  Dinner Dinner Dinner
sex    smoker
Male   Yes     17.645    NaN  12.16  27.280  20.29  23.33
       No      16.975    NaN    NaN  17.475  17.87  19.49
Female Yes     16.400    NaN  13.42  13.365  22.12  17.83
       No      13.290  18.78  15.98  22.750  17.07  17.15

In [25]:
from sklearn.datasets import *

In [26]:
data = load_iris()

In [27]:
type(data)

sklearn.utils._bunch.Bunch

In [28]:
data

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
        [5.5, 4.2, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.2],
        [5. , 3.2, 1.2, 0.2],
        [5.5, 3.5, 1.3, 0.2],
        [4.9, 3.6, 1.4, 0.1],
        [4.4, 3. , 1.3, 0.2],
        [5.1, 3.4, 1.5, 0.2],
        [5. , 3.5, 1.3, 0.3],
        [4.5, 2.3, 1.3, 0.3],
        [4.4, 3.2, 1.3, 0.2],
        [5. , 3.5, 1.6, 0.6],
        [5.1, 3.8, 1.9, 0.4],
        [4.8, 3. , 1.4, 0.3],
        [5.1, 3.8, 1.6, 0.2],
        [4.6, 3.2, 1.4, 0.2],
        [5.3, 3.7, 1.5, 0.2],
        [5. , 3.3, 1.4, 0.2],
        [7. , 3.2, 4.7, 1.4],
        [6.4, 3.2, 4.5, 1.5],
        [6.9, 3.1, 4.9, 1.5],
        [5.5, 2.3, 4. , 1.3],
        [6.5, 2.8, 4.6, 1.5],
        [5.7, 2.8, 4.5, 1.3],
        [6.3, 3.3, 4.7, 1.6],
        [4.9, 2.4, 3.3, 1. ],
        [6.6, 2.9, 4.6, 1.3],
        [5.2, 2.7, 3.9, 1.4],
        [5. , 2. , 3.5, 1. ],
        [5.9, 3. , 4.2, 1.5],
        [6. , 2.2, 4. , 1. ],
        [6.1, 2.9, 4.7, 1.4],
        [5.6, 2.9, 3.6, 1.3],
        [6.7, 3.1, 4.4, 1.4],
        [5.6, 3. , 4.5, 1.5],
        [5.8, 2.7, 4.1, 1. ],
        [6.2, 2.2, 4.5, 1.5],
        [5.6, 2.5, 3.9, 1.1],
        [5.9, 3.2, 4.8, 1.8],
        [6.1, 2.8, 4. , 1.3],
        [6.3, 2.5, 4.9, 1.5],
        [6.1, 2.8, 4.7, 1.2],
        [6.4, 2.9, 4.3, 1.3],
        [6.6, 3. , 4.4, 1.4],
        [6.8, 2.8, 4.8, 1.4],
        [6.7, 3. , 5. , 1.7],
        [6. , 2.9, 4.5, 1.5],
        [5.7, 2.6, 3.5, 1. ],
        [5.5, 2.4, 3.8, 1.1],
        [5.5, 2.4, 3.7, 1. ],
        [5.8, 2.7, 3.9, 1.2],
        [6. , 2.7, 5.1, 1.6],
        [5.4, 3. , 4.5, 1.5],
        [6. , 3.4, 4.5, 1.6],
        [6.7, 3.1, 4.7, 1.5],
        [6.3, 2.3, 4.4, 1.3],
        [5.6, 3. , 4.1, 1.3],
        [5.5, 2.5, 4. , 1.3],
        [5.5, 2.6, 4.4, 1.2],
        [6.1, 3. , 4.6, 1.4],
        [5.8, 2.6, 4. , 1.2],
        [5. , 2.3, 3.3, 1. ],
        [5.6, 2.7, 4.2, 1.3],
        [5.7, 3. , 4.2, 1.2],
        [5.7, 2.9, 4.2, 1.3],
        [6.2, 2.9, 4.3, 1.3],
        [5.1, 2.5, 3. , 1.1],
        [5.7, 2.8, 4.1, 1.3],
        [6.3, 3.3, 6. , 2.5],
        [5.8, 2.7, 5.1, 1.9],
        [7.1, 3. , 5.9, 2.1],
        [6.3, 2.9, 5.6, 1.8],
        [6.5, 3. , 5.8, 2.2],
        [7.6, 3. , 6.6, 2.1],
        [4.9, 2.5, 4.5, 1.7],
        [7.3, 2.9, 6.3, 1.8],
        [6.7, 2.5, 5.8, 1.8],
        [7.2, 3.6, 6.1, 2.5],
        [6.5, 3.2, 5.1, 2. ],
        [6.4, 2.7, 5.3, 1.9],
        [6.8, 3. , 5.5, 2.1],
        [5.7, 2.5, 5. , 2. ],
        [5.8, 2.8, 5.1, 2.4],
        [6.4, 3.2, 5.3, 2.3],
        [6.5, 3. , 5.5, 1.8],
        [7.7, 3.8, 6.7, 2.2],
        [7.7, 2.6, 6.9, 2.3],
        [6. , 2.2, 5. , 1.5],
        [6.9, 3.2, 5.7, 2.3],
        [5.6, 2.8, 4.9, 2. ],
        [7.7, 2.8, 6.7, 2. ],
        [6.3, 2.7, 4.9, 1.8],
        [6.7, 3.3, 5.7, 2.1],
        [7.2, 3.2, 6. , 1.8],
        [6.2, 2.8, 4.8, 1.8],
        [6.1, 3. , 4.9, 1.8],
        [6.4, 2.8, 5.6, 2.1],
        [7.2, 3. , 5.8, 1.6],
        [7.4, 2.8, 6.1, 1.9],
        [7.9, 3.8, 6.4, 2. ],
        [6.4, 2.8, 5.6, 2.2],
        [6.3, 2.8, 5.1, 1.5],
        [6.1, 2.6, 5.6, 1.4],
        [7.7, 3. , 6.1, 2.3],
        [6.3, 3.4, 5.6, 2.4],
        [6.4, 3.1, 5.5, 1.8],
        [6. , 3. , 4.8, 1.8],
        [6.9, 3.1, 5.4, 2.1],
        [6.7, 3.1, 5.6, 2.4],
        [6.9, 3.1, 5.1, 2.3],
        [5.8, 2.7, 5.1, 1.9],
        [6.8, 3.2, 5.9, 2.3],
        [6.7, 3.3, 5.7, 2.5],
        [6.7, 3. , 5.2, 2.3],
        [6.3, 2.5, 5. , 1.9],
        [6.5, 3. , 5.2, 2. ],
        [6.2, 3.4, 5.4, 2.3],
        [5.9, 3. , 5.1, 1.8]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]),
 'frame': None,
 'target_names': array(['setosa', 'versicolor', 'virginica'], dtype='<U10'),
 'DESCR': '.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 150 (50 in each of three classes)\n:Number of Attributes: 4 numeric, predictive attributes and the class\n:Attribute Information:\n    - sepal length in cm\n    - sepal width in cm\n    - petal length in cm\n    - petal width in cm\n    - class:\n            - Iris-Setosa\n            - Iris-Versicolour\n            - Iris-Virginica\n\n:Summary Statistics:\n\n============== ==== ==== ======= ===== ====================\n                Min  Max   Mean    SD   Class Correlation\n============== ==== ==== ======= ===== ====================\nsepal length:   4.3  7.9   5.84   0.83    0.7826\nsepal width:    2.0  4.4   3.05   0.43   -0.4194\npetal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\npetal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n============== ==== ==== ======= ===== ====================\n\n:Missing Attribute Values: None\n:Class Distribution: 33.3% for each of 3 classes.\n:Creator: R.A. Fisher\n:Donor: Michael Marshall (MARSHALL%PLU@io.arc.nasa.gov)\n:Date: July, 1988\n\nThe famous Iris database, first used by Sir R.A. Fisher. The dataset is taken\nfrom Fisher\'s paper. Note that it\'s the same as in R, but not as in the UCI\nMachine Learning Repository, which has two wrong data points.\n\nThis is perhaps the best known database to be found in the\npattern recognition literature.  Fisher\'s paper is a classic in the field and\nis referenced frequently to this day.  (See Duda & Hart, for example.)  The\ndata set contains 3 classes of 50 instances each, where each class refers to a\ntype of iris plant.  One class is linearly separable from the other 2; the\nlatter are NOT linearly separable from each other.\n\n|details-start|\n**References**\n|details-split|\n\n- Fisher, R.A. "The use of multiple measurements in taxonomic problems"\n  Annual Eugenics, 7, Part II, 179-188 (1936); also in "Contributions to\n  Mathematical Statistics" (John Wiley, NY, 1950).\n- Duda, R.O., & Hart, P.E. (1973) Pattern Classification and Scene Analysis.\n  (Q327.D83) John Wiley & Sons.  ISBN 0-471-22361-1.  See page 218.\n- Dasarathy, B.V. (1980) "Nosing Around the Neighborhood: A New System\n  Structure and Classification Rule for Recognition in Partially Exposed\n  Environments".  IEEE Transactions on Pattern Analysis and Machine\n  Intelligence, Vol. PAMI-2, No. 1, 67-71.\n- Gates, G.W. (1972) "The Reduced Nearest Neighbor Rule".  IEEE Transactions\n  on Information Theory, May 1972, 431-433.\n- See also: 1988 MLC Proceedings, 54-64.  Cheeseman et al"s AUTOCLASS II\n  conceptual clustering system finds 3 classes in the data.\n- Many, many more ...\n\n|details-end|\n',
 'feature_names': ['sepal length (cm)',
  'sepal width (cm)',
  'petal length (cm)',
  'petal width (cm)'],
 'filename': 'iris.csv',
 'data_module': 'sklearn.datasets.data'}

In [30]:
data.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [32]:
data['feature_names']

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [31]:
data['data']

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.2],
       [5. , 3.2, 1.2, 0.2],
       [5.5, 3.5, 1.3, 0.2],
       [4.9, 3.6, 1.4, 0.1],
       [4.4, 3. , 1.3, 0.2],
       [5.1, 3.4, 1.5, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [4.5, 2.3, 1.3, 0.3],
       [4.4, 3.2, 1.3, 0.2],
       [5. , 3.5, 1.6, 0.6],
       [5.1, 3.8, 1.9, 0.4],
       [4.8, 3. , 1.4, 0.3],
       [5.1, 3.8, 1.6, 0.2],
       [4.6, 3.2, 1.4, 0.2],
       [5.3, 3.7, 1.5, 0.2],
       [5. , 3.3, 1.4, 0.2],
       [7. , 3.2, 4.7, 1.4],
       [6.4, 3.2, 4.5, 1.5],
       [6.9, 3.1, 4.9, 1.5],
       [5.5, 2.3, 4. , 1.3],
       [6.5, 2.8, 4.6, 1.5],
       [5.7, 2.8, 4.5, 1.3],
       [6.3, 3.3, 4.7, 1.6],
       [4.9, 2.4, 3.3, 1. ],
       [6.6, 2.9, 4.6, 1.3],
       [5.2, 2.7, 3.9, 1.4],
       [5. , 2. , 3.5, 1. ],
       [5.9, 3. , 4.2, 1.5],
       [6. , 2.2, 4. , 1. ],
       [6.1, 2.9, 4.7, 1.4],
       [5.6, 2.9, 3.6, 1.3],
       [6.7, 3.1, 4.4, 1.4],
       [5.6, 3. , 4.5, 1.5],
       [5.8, 2.7, 4.1, 1. ],
       [6.2, 2.2, 4.5, 1.5],
       [5.6, 2.5, 3.9, 1.1],
       [5.9, 3.2, 4.8, 1.8],
       [6.1, 2.8, 4. , 1.3],
       [6.3, 2.5, 4.9, 1.5],
       [6.1, 2.8, 4.7, 1.2],
       [6.4, 2.9, 4.3, 1.3],
       [6.6, 3. , 4.4, 1.4],
       [6.8, 2.8, 4.8, 1.4],
       [6.7, 3. , 5. , 1.7],
       [6. , 2.9, 4.5, 1.5],
       [5.7, 2.6, 3.5, 1. ],
       [5.5, 2.4, 3.8, 1.1],
       [5.5, 2.4, 3.7, 1. ],
       [5.8, 2.7, 3.9, 1.2],
       [6. , 2.7, 5.1, 1.6],
       [5.4, 3. , 4.5, 1.5],
       [6. , 3.4, 4.5, 1.6],
       [6.7, 3.1, 4.7, 1.5],
       [6.3, 2.3, 4.4, 1.3],
       [5.6, 3. , 4.1, 1.3],
       [5.5, 2.5, 4. , 1.3],
       [5.5, 2.6, 4.4, 1.2],
       [6.1, 3. , 4.6, 1.4],
       [5.8, 2.6, 4. , 1.2],
       [5. , 2.3, 3.3, 1. ],
       [5.6, 2.7, 4.2, 1.3],
       [5.7, 3. , 4.2, 1.2],
       [5.7, 2.9, 4.2, 1.3],
       [6.2, 2.9, 4.3, 1.3],
       [5.1, 2.5, 3. , 1.1],
       [5.7, 2.8, 4.1, 1.3],
       [6.3, 3.3, 6. , 2.5],
       [5.8, 2.7, 5.1, 1.9],
       [7.1, 3. , 5.9, 2.1],
       [6.3, 2.9, 5.6, 1.8],
       [6.5, 3. , 5.8, 2.2],
       [7.6, 3. , 6.6, 2.1],
       [4.9, 2.5, 4.5, 1.7],
       [7.3, 2.9, 6.3, 1.8],
       [6.7, 2.5, 5.8, 1.8],
       [7.2, 3.6, 6.1, 2.5],
       [6.5, 3.2, 5.1, 2. ],
       [6.4, 2.7, 5.3, 1.9],
       [6.8, 3. , 5.5, 2.1],
       [5.7, 2.5, 5. , 2. ],
       [5.8, 2.8, 5.1, 2.4],
       [6.4, 3.2, 5.3, 2.3],
       [6.5, 3. , 5.5, 1.8],
       [7.7, 3.8, 6.7, 2.2],
       [7.7, 2.6, 6.9, 2.3],
       [6. , 2.2, 5. , 1.5],
       [6.9, 3.2, 5.7, 2.3],
       [5.6, 2.8, 4.9, 2. ],
       [7.7, 2.8, 6.7, 2. ],
       [6.3, 2.7, 4.9, 1.8],
       [6.7, 3.3, 5.7, 2.1],
       [7.2, 3.2, 6. , 1.8],
       [6.2, 2.8, 4.8, 1.8],
       [6.1, 3. , 4.9, 1.8],
       [6.4, 2.8, 5.6, 2.1],
       [7.2, 3. , 5.8, 1.6],
       [7.4, 2.8, 6.1, 1.9],
       [7.9, 3.8, 6.4, 2. ],
       [6.4, 2.8, 5.6, 2.2],
       [6.3, 2.8, 5.1, 1.5],
       [6.1, 2.6, 5.6, 1.4],
       [7.7, 3. , 6.1, 2.3],
       [6.3, 3.4, 5.6, 2.4],
       [6.4, 3.1, 5.5, 1.8],
       [6. , 3. , 4.8, 1.8],
       [6.9, 3.1, 5.4, 2.1],
       [6.7, 3.1, 5.6, 2.4],
       [6.9, 3.1, 5.1, 2.3],
       [5.8, 2.7, 5.1, 1.9],
       [6.8, 3.2, 5.9, 2.3],
       [6.7, 3.3, 5.7, 2.5],
       [6.7, 3. , 5.2, 2.3],
       [6.3, 2.5, 5. , 1.9],
       [6.5, 3. , 5.2, 2. ],
       [6.2, 3.4, 5.4, 2.3],
       [5.9, 3. , 5.1, 1.8]])

In [33]:
df = pd.DataFrame(data = data['data'], columns = data['feature_names'])

In [35]:
df.sample(20)

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
124                6.7               3.3                5.7               2.1
111                6.4               2.7                5.3               1.9
42                 4.4               3.2                1.3               0.2
149                5.9               3.0                5.1               1.8
59                 5.2               2.7                3.9               1.4
60                 5.0               2.0                3.5               1.0
109                7.2               3.6                6.1               2.5
33                 5.5               4.2                1.4               0.2
140                6.7               3.1                5.6               2.4
1                  4.9               3.0                1.4               0.2
37                 4.9               3.6                1.4               0.1
44                 5.1               3.8                1.9               0.4
12                 4.8               3.0                1.4               0.1
113                5.7               2.5                5.0               2.0
82                 5.8               2.7                3.9               1.2
77                 6.7               3.0                5.0               1.7
135                7.7               3.0                6.1               2.3
90                 5.5               2.6                4.4               1.2
147                6.5               3.0                5.2               2.0
4                  5.0               3.6                1.4               0.2

In [37]:
df['target'] = data['target']

In [39]:
df.head(10)

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
5,5.4,3.9,1.7,0.4,0
6,4.6,3.4,1.4,0.3,0
7,5.0,3.4,1.5,0.2,0
8,4.4,2.9,1.4,0.2,0
9,4.9,3.1,1.5,0.1,0

In [40]:
data['target_names']

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [44]:
df['flower_name'] = data['target_names'][df['target']]

In [45]:
df

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target,flower_name
0,5.1,3.5,1.4,0.2,0,setosa
1,4.9,3.0,1.4,0.2,0,setosa
2,4.7,3.2,1.3,0.2,0,setosa
3,4.6,3.1,1.5,0.2,0,setosa
4,5.0,3.6,1.4,0.2,0,setosa
...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2,virginica
146,6.3,2.5,5.0,1.9,2,virginica
147,6.5,3.0,5.2,2.0,2,virginica
148,6.2,3.4,5.4,2.3,2,virginica
149,5.9,3.0,5.1,1.8,2,virginica

In [47]:
df.groupby('flower_name')['sepal length (cm)'].mean()

flower_name
setosa        5.006
versicolor    5.936
virginica     6.588
Name: sepal length (cm), dtype: float64

In [48]:
import kagglehub
import os
# Download latest version
path = kagglehub.dataset_download("vivekmali1436/banking-transactions-dataset")

print("Path to dataset files:", path)

os.listdir(path)

c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Downloading to C:\Users\Admin\.cache\kagglehub\datasets\vivekmali1436\banking-transactions-dataset\1.archive...

100%|██████████| 89.4M/89.4M [00:07<00:00, 12.1MB/s]

Extracting files...

Path to dataset files: C:\Users\Admin\.cache\kagglehub\datasets\vivekmali1436\banking-transactions-dataset\versions\1

['accounts.csv',
 'branches.csv',
 'cards.csv',
 'card_transactions.csv',
 'customers.csv',
 'employees.csv',
 'loans.csv',
 'loan_payments.csv',
 'support_tickets.csv',
 'transactions.csv']

In [49]:
path

'C:\\Users\\Admin\\.cache\\kagglehub\\datasets\\vivekmali1436\\banking-transactions-dataset\\versions\\1'

In [55]:
pd.read_csv(path + '/' + os.listdir(path)[3])

         card_txn_id  card_id    txn_date merchant_category   amount  is_fraud
0                  1    52505  2025-01-28         Education  2162.41         0
1                  2    12716  2022-08-26         Education  2236.55         0
2                  3    49060  2019-10-07            Travel  1184.59         0
3                  4    18295  2019-03-07            Travel   124.79         0
4                  5    54342  2026-03-26         Insurance   546.10         0
...              ...      ...         ...               ...      ...       ...
2999995      2999996    35925  2019-05-02     Entertainment   655.20         0
2999996      2999997    23555  2023-01-17          Shopping   775.03         0
2999997      2999998    17322  2025-02-10          Shopping   669.16         0
2999998      2999999    31765  2018-04-27         Education   449.14         0
2999999      3000000    59784  2018-09-15         Education  2524.09         0

[3000000 rows x 6 columns]

In [1]:
pip install dtale

Collecting dtale
  Downloading dtale-3.22.0-py2.py3-none-any.whl.metadata (16 kB)
Collecting lz4 (from dtale)
  Downloading lz4-4.4.5-cp311-cp311-win_amd64.whl.metadata (3.9 kB)
Requirement already satisfied: beautifulsoup4!=4.13.0b2 in c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from dtale) (4.12.3)
Requirement already satisfied: certifi in c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from dtale) (2023.11.17)
Requirement already satisfied: cycler in c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from dtale) (0.12.1)
Collecting dash (from dtale)
  Downloading dash-4.4.1-py3-none-any.whl.metadata (11 kB)
Collecting dash-bootstrap-components (from dtale)
  Downloading dash_bootstrap_components-2.0.4-py3-none-any.whl.metadata (18 kB)
Collecting et_xmlfile (from dtale)
  Using cached et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Requirement already satisfied: Flask in c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from dtale) (3.0.0)
Collecting Flask-Compress (from dtale)
  Downloading flask_compress-1.24-py3-none-any.whl.metadata (11 kB)
Collecting future>=0.14.0 (from dtale)
  Downloading future-1.0.0-py3-none-any.whl.metadata (4.0 kB)
Requirement already satisfied: itsdangerous in c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from dtale) (2.1.2)
Collecting kaleido (from dtale)
  Downloading kaleido-1.3.0-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: matplotlib in c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from dtale) (3.8.3)
Collecting missingno (from dtale)
  Downloading missingno-0.5.2-py3-none-any.whl.metadata (639 bytes)
Collecting networkx (from dtale)
  Using cached networkx-3.6.1-py3-none-any.whl.metadata (6.8 kB)
Requirement already satisfied: numpy in c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from dtale) (1.26.2)
Collecting openpyxl!=3.2.0b1 (from dtale)
  Using cached openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: packaging in c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from dtale) (23.2)
Requirement already satisfied: pandas in c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from dtale) (2.2.1)
Collecting pkginfo (from dtale)
  Downloading pkginfo-1.12.1.2-py3-none-any.whl.metadata (13 kB)
Collecting plotly (from dtale)
  Downloading plotly-7.0.0-py3-none-any.whl.metadata (8.7 kB)
Requirement already satisfied: requests in c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from dtale) (2.31.0)
Requirement already satisfied: scikit-learn in c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from dtale) (1.4.0)
Requirement already satisfied: scipy in c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from dtale) (1.12.0)
Requirement already satisfied: seaborn in c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from dtale) (0.13.2)
Collecting squarify (from dtale)
  Downloading squarify-0.4.4-py3-none-any.whl.metadata (600 bytes)
Collecting statsmodels (from dtale)
  Downloading statsmodels-0.15.0-cp311-cp311-win_amd64.whl.metadata (9.6 kB)
Collecting strsimpy (from dtale)
  Downloading strsimpy-0.2.1-py3-none-any.whl.metadata (20 kB)
Requirement already satisfied: six in c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from dtale) (1.16.0)
Requirement already satisfied: werkzeug in c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from dtale) (3.0.0)
Collecting xarray (from dtale)
  Downloading xarray-2026.7.0-py3-none-any.whl.metadata (12 kB)
Collecting xlrd (from dtale)
  Downloading xlrd-2.0.2-py2.py3-none-any.whl.metadata (3.5 kB)
Requirement already satisfied: soupsieve>1.2 in c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from beautifulsoup4!=4.13.0b2->dtale) (2.5)
Requirement already satisfied: importlib-metadata in c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from dash->dtale) (7.0.1)
Requirement already satisfied: typing_extensions>=4.1.1 in c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from dash->dtale) (4.9.0)
Collecting retrying (from dash->dtale)
  Downloading retrying-1.4.2-py3-none-any.whl.metadata (5.5 kB)
Requirement already satisfied: nest-asyncio in c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from dash->dtale) (1.6.0)
Requirement already satisfied: setuptools in c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from dash->dtale) (65.5.0)
Collecting janus>=1.0.0 (from dash->dtale)
  Downloading janus-2.0.0-py3-none-any.whl.metadata (5.3 kB)
Collecting pydantic>=2.10 (from dash->dtale)
  Using cached pydantic-2.13.5-py3-none-any.whl.metadata (110 kB)
Requirement already satisfied: comm in c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from dash->dtale) (0.2.1)
Requirement already satisfied: Jinja2>=3.1.2 in c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from Flask->dtale) (3.1.2)
Requirement already satisfied: click>=8.1.3 in c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from Flask->dtale) (8.1.7)
Requirement already satisfied: blinker>=1.6.2 in c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from Flask->dtale) (1.6.3)
Requirement already satisfied: MarkupSafe>=2.1.1 in c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from werkzeug->dtale) (2.1.3)
Requirement already satisfied: colorama in c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from click>=8.1.3->Flask->dtale) (0.4.6)
Collecting narwhals>=1.15.1 (from plotly->dtale)
  Downloading narwhals-2.25.0-py3-none-any.whl.metadata (15 kB)
Collecting annotated-types>=0.6.0 (from pydantic>=2.10->dash->dtale)
  Using cached annotated_types-0.8.0-py3-none-any.whl.metadata (15 kB)
Collecting pydantic-core==2.46.5 (from pydantic>=2.10->dash->dtale)
  Downloading pydantic_core-2.46.5-cp311-cp311-win_amd64.whl.metadata (6.7 kB)
Collecting typing_extensions>=4.1.1 (from dash->dtale)
  Using cached typing_extensions-4.16.0-py3-none-any.whl.metadata (3.3 kB)
Collecting typing-inspection>=0.4.2 (from pydantic>=2.10->dash->dtale)
  Using cached typing_inspection-0.4.4-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: traitlets>=4 in c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from comm->dash->dtale) (5.14.1)
Collecting brotli (from Flask-Compress->dtale)
  Using cached brotli-1.2.0-cp311-cp311-win_amd64.whl.metadata (6.3 kB)
Collecting backports.zstd (from Flask-Compress->dtale)
  Downloading backports_zstd-1.7.0-cp311-cp311-win_amd64.whl.metadata (7.0 kB)
Requirement already satisfied: zipp>=0.5 in c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from importlib-metadata->dash->dtale) (3.17.0)
Collecting choreographer>=1.3.0 (from kaleido->dtale)
  Downloading choreographer-1.3.0-py3-none-any.whl.metadata (6.9 kB)
Collecting logistro>=1.0.8 (from kaleido->dtale)
  Downloading logistro-2.0.1-py3-none-any.whl.metadata (3.9 kB)
Collecting orjson>=3.10.15 (from kaleido->dtale)
  Downloading orjson-3.12.0-cp311-cp311-win_amd64.whl.metadata (43 kB)
Collecting platformdirs>=4.3.6 (from choreographer>=1.3.0->kaleido->dtale)
  Using cached platformdirs-4.11.5-py3-none-any.whl.metadata (5.5 kB)
Collecting simplejson>=3.19.3 (from choreographer>=1.3.0->kaleido->dtale)
  Downloading simplejson-4.1.2-cp311-cp311-win_amd64.whl.metadata (3.9 kB)
Requirement already satisfied: contourpy>=1.0.1 in c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from matplotlib->dtale) (1.2.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from matplotlib->dtale) (4.48.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from matplotlib->dtale) (1.4.5)
Requirement already satisfied: pillow>=8 in c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from matplotlib->dtale) (10.2.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from matplotlib->dtale) (3.1.1)
Requirement already satisfied: python-dateutil>=2.7 in c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from matplotlib->dtale) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from pandas->dtale) (2023.4)
Requirement already satisfied: tzdata>=2022.7 in c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from pandas->dtale) (2023.4)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from requests->dtale) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from requests->dtale) (2.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from requests->dtale) (2.1.0)
Requirement already satisfied: joblib>=1.2.0 in c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from scikit-learn->dtale) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from scikit-learn->dtale) (3.2.0)
Collecting patsy>=0.5.6 (from statsmodels->dtale)
  Downloading patsy-1.0.2-py2.py3-none-any.whl.metadata (3.6 kB)
Collecting formulaic>=1.1.0 (from statsmodels->dtale)
  Downloading formulaic-1.2.2-py3-none-any.whl.metadata (7.0 kB)
Collecting interface-meta>=1.2.0 (from formulaic>=1.1.0->statsmodels->dtale)
  Downloading interface_meta-2.0.1-py3-none-any.whl.metadata (6.4 kB)
Requirement already satisfied: wrapt>=1.0 in c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from formulaic>=1.1.0->statsmodels->dtale) (1.14.1)
Collecting packaging (from dtale)
  Using cached packaging-26.3-py3-none-any.whl.metadata (3.5 kB)
Downloading dtale-3.22.0-py2.py3-none-any.whl (17.4 MB)
   ---------------------------------------- 0.0/17.4 MB ? eta -:--:--
   - -------------------------------------- 0.5/17.4 MB 3.4 MB/s eta 0:00:06
   --- ------------------------------------ 1.3/17.4 MB 3.4 MB/s eta 0:00:05
   ---- ----------------------------------- 1.8/17.4 MB 3.0 MB/s eta 0:00:06
   ----- ---------------------------------- 2.4/17.4 MB 3.0 MB/s eta 0:00:06
   ------- -------------------------------- 3.1/17.4 MB 3.2 MB/s eta 0:00:05
   --------- ------------------------------ 4.2/17.4 MB 3.4 MB/s eta 0:00:04
   ---------- ----------------------------- 4.7/17.4 MB 3.4 MB/s eta 0:00:04
   ------------ --------------------------- 5.5/17.4 MB 3.5 MB/s eta 0:00:04
   -------------- ------------------------- 6.3/17.4 MB 3.5 MB/s eta 0:00:04
   ---------------- ----------------------- 7.1/17.4 MB 3.5 MB/s eta 0:00:03
   ------------------ --------------------- 7.9/17.4 MB 3.6 MB/s eta 0:00:03
   -------------------- ------------------- 8.9/17.4 MB 3.6 MB/s eta 0:00:03
   --------------------- ------------------ 9.4/17.4 MB 3.6 MB/s eta 0:00:03
   ---------------------- ----------------- 10.0/17.4 MB 3.5 MB/s eta 0:00:03
   ------------------------ --------------- 10.7/17.4 MB 3.5 MB/s eta 0:00:02
   ------------------------- -------------- 11.3/17.4 MB 3.5 MB/s eta 0:00:02
   --------------------------- ------------ 12.1/17.4 MB 3.5 MB/s eta 0:00:02
   ------------------------------ --------- 13.1/17.4 MB 3.5 MB/s eta 0:00:02
   ------------------------------- -------- 13.6/17.4 MB 3.6 MB/s eta 0:00:02
   --------------------------------- ------ 14.4/17.4 MB 3.5 MB/s eta 0:00:01
   ---------------------------------- ----- 15.2/17.4 MB 3.5 MB/s eta 0:00:01
   ------------------------------------ --- 16.0/17.4 MB 3.5 MB/s eta 0:00:01
   -------------------------------------- - 16.5/17.4 MB 3.6 MB/s eta 0:00:01
   ---------------------------------------  17.3/17.4 MB 3.5 MB/s eta 0:00:01
   ---------------------------------------- 17.4/17.4 MB 3.4 MB/s  0:00:05
Downloading future-1.0.0-py3-none-any.whl (491 kB)
Using cached openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading dash-4.4.1-py3-none-any.whl (8.9 MB)
   ---------------------------------------- 0.0/8.9 MB ? eta -:--:--
   --- ------------------------------------ 0.8/8.9 MB 4.8 MB/s eta 0:00:02
   -------- ------------------------------- 1.8/8.9 MB 4.6 MB/s eta 0:00:02
   ----------- ---------------------------- 2.6/8.9 MB 4.4 MB/s eta 0:00:02
   --------------- ------------------------ 3.4/8.9 MB 4.2 MB/s eta 0:00:02
   ------------------ --------------------- 4.2/8.9 MB 4.3 MB/s eta 0:00:02
   ----------------------- ---------------- 5.2/8.9 MB 4.3 MB/s eta 0:00:01
   -------------------------- ------------- 6.0/8.9 MB 4.3 MB/s eta 0:00:01
   ------------------------------ --------- 6.8/8.9 MB 4.3 MB/s eta 0:00:01
   --------------------------------- ------ 7.6/8.9 MB 4.3 MB/s eta 0:00:01
   ------------------------------------- -- 8.4/8.9 MB 4.2 MB/s eta 0:00:01
   ---------------------------------------- 8.9/8.9 MB 4.1 MB/s  0:00:02
Downloading janus-2.0.0-py3-none-any.whl (12 kB)
Downloading plotly-7.0.0-py3-none-any.whl (9.1 MB)
   ---------------------------------------- 0.0/9.1 MB ? eta -:--:--
   --- ------------------------------------ 0.8/9.1 MB 4.2 MB/s eta 0:00:02
   ------ --------------------------------- 1.6/9.1 MB 3.8 MB/s eta 0:00:02
   --------- ------------------------------ 2.1/9.1 MB 3.9 MB/s eta 0:00:02
   ---------- ----------------------------- 2.4/9.1 MB 3.0 MB/s eta 0:00:03
   --------------- ------------------------ 3.4/9.1 MB 3.3 MB/s eta 0:00:02
   ------------------ --------------------- 4.2/9.1 MB 3.4 MB/s eta 0:00:02
   ---------------------- ----------------- 5.0/9.1 MB 3.5 MB/s eta 0:00:02
   -------------------------- ------------- 6.0/9.1 MB 3.6 MB/s eta 0:00:01
   ---------------------------- ----------- 6.6/9.1 MB 3.6 MB/s eta 0:00:01
   --------------------------------- ------ 7.6/9.1 MB 3.7 MB/s eta 0:00:01
   ------------------------------------- -- 8.4/9.1 MB 3.7 MB/s eta 0:00:01
   ---------------------------------------- 9.1/9.1 MB 3.6 MB/s  0:00:02
Downloading narwhals-2.25.0-py3-none-any.whl (467 kB)
Downloading pydantic-2.13.5-py3-none-any.whl (472 kB)
Downloading pydantic_core-2.46.5-cp311-cp311-win_amd64.whl (2.0 MB)
   ---------------------------------------- 0.0/2.0 MB ? eta -:--:--
   --------------- ------------------------ 0.8/2.0 MB 4.8 MB/s eta 0:00:01
   ------------------------------ --------- 1.6/2.0 MB 4.4 MB/s eta 0:00:01
   ---------------------------------------- 2.0/2.0 MB 3.9 MB/s  0:00:00
Using cached annotated_types-0.8.0-py3-none-any.whl (13 kB)
Using cached typing_extensions-4.16.0-py3-none-any.whl (45 kB)
Using cached typing_inspection-0.4.4-py3-none-any.whl (14 kB)
Downloading dash_bootstrap_components-2.0.4-py3-none-any.whl (204 kB)
Using cached et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Downloading flask_compress-1.24-py3-none-any.whl (11 kB)
Downloading backports_zstd-1.7.0-cp311-cp311-win_amd64.whl (329 kB)
Using cached brotli-1.2.0-cp311-cp311-win_amd64.whl (369 kB)
Downloading kaleido-1.3.0-py3-none-any.whl (55 kB)
Downloading choreographer-1.3.0-py3-none-any.whl (52 kB)
Downloading logistro-2.0.1-py3-none-any.whl (8.6 kB)
Downloading orjson-3.12.0-cp311-cp311-win_amd64.whl (122 kB)
Using cached platformdirs-4.11.5-py3-none-any.whl (23 kB)
Downloading simplejson-4.1.2-cp311-cp311-win_amd64.whl (91 kB)
Downloading lz4-4.4.5-cp311-cp311-win_amd64.whl (99 kB)
Downloading missingno-0.5.2-py3-none-any.whl (8.7 kB)
Using cached networkx-3.6.1-py3-none-any.whl (2.1 MB)
Downloading pkginfo-1.12.1.2-py3-none-any.whl (32 kB)
Downloading retrying-1.4.2-py3-none-any.whl (10 kB)
Downloading squarify-0.4.4-py3-none-any.whl (4.1 kB)
Downloading statsmodels-0.15.0-cp311-cp311-win_amd64.whl (11.4 MB)
   ---------------------------------------- 0.0/11.4 MB ? eta -:--:--
   -- ------------------------------------- 0.8/11.4 MB 4.2 MB/s eta 0:00:03
   ----- ---------------------------------- 1.6/11.4 MB 4.0 MB/s eta 0:00:03
   -------- ------------------------------- 2.4/11.4 MB 3.9 MB/s eta 0:00:03
   ---------- ----------------------------- 2.9/11.4 MB 3.6 MB/s eta 0:00:03
   ------------ --------------------------- 3.7/11.4 MB 3.7 MB/s eta 0:00:03
   --------------- ------------------------ 4.5/11.4 MB 3.6 MB/s eta 0:00:02
   ------------------ --------------------- 5.2/11.4 MB 3.6 MB/s eta 0:00:02
   --------------------- ------------------ 6.0/11.4 MB 3.7 MB/s eta 0:00:02
   ----------------------- ---------------- 6.8/11.4 MB 3.6 MB/s eta 0:00:02
   -------------------------- ------------- 7.6/11.4 MB 3.7 MB/s eta 0:00:02
   ----------------------------- ---------- 8.4/11.4 MB 3.7 MB/s eta 0:00:01
   --------------------------------- ------ 9.4/11.4 MB 3.8 MB/s eta 0:00:01
   ----------------------------------- ---- 10.2/11.4 MB 3.8 MB/s eta 0:00:01
   ------------------------------------- -- 10.7/11.4 MB 3.8 MB/s eta 0:00:01
   ---------------------------------------- 11.4/11.4 MB 3.6 MB/s  0:00:03
Downloading formulaic-1.2.2-py3-none-any.whl (118 kB)
Downloading interface_meta-2.0.1-py3-none-any.whl (15 kB)
Downloading patsy-1.0.2-py2.py3-none-any.whl (233 kB)
Downloading strsimpy-0.2.1-py3-none-any.whl (45 kB)
Downloading xarray-2026.7.0-py3-none-any.whl (1.4 MB)
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   -------------- ------------------------- 0.5/1.4 MB 3.3 MB/s eta 0:00:01
   ------------------------------------ --- 1.3/1.4 MB 3.7 MB/s eta 0:00:01
   ---------------------------------------- 1.4/1.4 MB 3.2 MB/s  0:00:00
Using cached packaging-26.3-py3-none-any.whl (129 kB)
Downloading xlrd-2.0.2-py2.py3-none-any.whl (96 kB)
Installing collected packages: strsimpy, squarify, brotli, xlrd, typing_extensions, simplejson, retrying, platformdirs, pkginfo, patsy, packaging, orjson, networkx, narwhals, lz4, logistro, janus, interface-meta, future, et_xmlfile, backports.zstd, annotated-types, typing-inspection, pydantic-core, plotly, openpyxl, choreographer, xarray, pydantic, kaleido, formulaic, Flask-Compress, statsmodels, missingno, dash, dash-bootstrap-components, dtale

   ----------------------------------------  0/37 [strsimpy]
   ----------------------------------------  0/37 [strsimpy]
   ----------------------------------------  0/37 [strsimpy]
   ----------------------------------------  0/37 [strsimpy]
   ----------------------------------------  0/37 [strsimpy]
   --- ------------------------------------  3/37 [xlrd]
   --- ------------------------------------  3/37 [xlrd]
   --- ------------------------------------  3/37 [xlrd]
   --- ------------------------------------  3/37 [xlrd]
  Attempting uninstall: typing_extensions
   --- ------------------------------------  3/37 [xlrd]
   ---- -----------------------------------  4/37 [typing_extensions]
    Found existing installation: typing_extensions 4.9.0
   ---- -----------------------------------  4/37 [typing_extensions]
    Uninstalling typing_extensions-4.9.0:
   ---- -----------------------------------  4/37 [typing_extensions]
   ---- -----------------------------------  4/37 [typing_extensions]
   ---- -----------------------------------  4/37 [typing_extensions]
   ---- -----------------------------------  4/37 [typing_extensions]
   ---- -----------------------------------  4/37 [typing_extensions]
   ---- -----------------------------------  4/37 [typing_extensions]

WARNING: Ignoring invalid distribution ~andas (c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~andas (c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages)
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
jupyterlab 4.1.4 requires httpx>=0.25.0, but you have httpx 0.13.3 which is incompatible.
streamlit 1.31.0 requires packaging<24,>=16.8, but you have packaging 26.3 which is incompatible.
WARNING: Ignoring invalid distribution ~andas (c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages)

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

   ------------------- -------------------- 18/37 [future]
   ------------------- -------------------- 18/37 [future]
   ------------------- -------------------- 18/37 [future]
   ------------------- -------------------- 18/37 [future]
   ------------------- -------------------- 18/37 [future]
   ------------------- -------------------- 18/37 [future]
   ------------------- -------------------- 18/37 [future]
   ------------------- -------------------- 18/37 [future]
   ------------------- -------------------- 18/37 [future]
   ------------------- -------------------- 18/37 [future]
   ------------------- -------------------- 18/37 [future]
   ------------------- -------------------- 18/37 [future]
   ------------------- -------------------- 18/37 [future]
   ------------------- -------------------- 18/37 [future]
   ------------------- -------------------- 18/37 [future]
   ------------------- -------------------- 18/37 [future]
   ------------------- -------------------- 18/37 [future]
   ------------------- -------------------- 18/37 [future]
   ------------------- -------------------- 18/37 [future]
   ------------------- -------------------- 18/37 [future]
   ------------------- -------------------- 18/37 [future]
   ------------------- -------------------- 18/37 [future]
   ------------------- -------------------- 18/37 [future]
   ------------------- -------------------- 18/37 [future]
   ------------------- -------------------- 18/37 [future]
   ------------------- -------------------- 18/37 [future]
   ------------------- -------------------- 18/37 [future]
   ------------------- -------------------- 18/37 [future]
   ------------------- -------------------- 18/37 [future]
   ------------------- -------------------- 18/37 [future]
   ------------------- -------------------- 18/37 [future]
   ------------------- -------------------- 18/37 [future]
   ------------------- -------------------- 18/37 [future]
   -------------------- ------------------- 19/37 [et_xmlfile]
   --------------------- ------------------ 20/37 [backports.zstd]
   --------------------- ------------------ 20/37 [backports.zstd]
   --------------------- ------------------ 20/37 [backports.zstd]
   --------------------- ------------------ 20/37 [backports.zstd]
   --------------------- ------------------ 20/37 [backports.zstd]
   ---------------------- ----------------- 21/37 [annotated-types]
   ----------------------- ---------------- 22/37 [typing-inspection]
   ------------------------ --------------- 23/37 [pydantic-core]
   ------------------------ --------------- 23/37 [pydantic-core]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]
   ------------------------- -------------- 24/37 [plotly]

In [2]:
import pandas as pd
import dtale

df = pd.read_csv(r"C:\Users\Admin\Desktop\projects\Data Science-1pm\Pandas\insurance.csv")

In [6]:
# dtale.USE_COLAB = True
# dtale.show(df)

In [1]:
import os 
import kagglehub
import pandas as pd
path = kagglehub.dataset_download("neuromusic/avocado-prices")


df = pd.read_csv(path + "/" + os.listdir(path)[0])
df.head()

c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

,Unnamed: 0,Date,AveragePrice,Total Volume,4046,4225,4770,Total Bags,Small Bags,Large Bags,XLarge Bags,type,year,region
0,0,2015-12-27,1.33,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,conventional,2015,Albany
1,1,2015-12-20,1.35,54876.98,674.28,44638.81,58.33,9505.56,9408.07,97.49,0.0,conventional,2015,Albany
2,2,2015-12-13,0.93,118220.22,794.70,109149.67,130.50,8145.35,8042.21,103.14,0.0,conventional,2015,Albany
3,3,2015-12-06,1.08,78992.15,1132.00,71976.41,72.58,5811.16,5677.40,133.76,0.0,conventional,2015,Albany
4,4,2015-11-29,1.28,51039.60,941.48,43838.39,75.78,6183.95,5986.26,197.69,0.0,conventional,2015,Albany

In [2]:
df

,Unnamed: 0,Date,AveragePrice,Total Volume,4046,4225,4770,Total Bags,Small Bags,Large Bags,XLarge Bags,type,year,region
0,0,2015-12-27,1.33,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,conventional,2015,Albany
1,1,2015-12-20,1.35,54876.98,674.28,44638.81,58.33,9505.56,9408.07,97.49,0.0,conventional,2015,Albany
2,2,2015-12-13,0.93,118220.22,794.70,109149.67,130.50,8145.35,8042.21,103.14,0.0,conventional,2015,Albany
3,3,2015-12-06,1.08,78992.15,1132.00,71976.41,72.58,5811.16,5677.40,133.76,0.0,conventional,2015,Albany
4,4,2015-11-29,1.28,51039.60,941.48,43838.39,75.78,6183.95,5986.26,197.69,0.0,conventional,2015,Albany
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18244,7,2018-02-04,1.63,17074.83,2046.96,1529.20,0.00,13498.67,13066.82,431.85,0.0,organic,2018,WestTexNewMexico
18245,8,2018-01-28,1.71,13888.04,1191.70,3431.50,0.00,9264.84,8940.04,324.80,0.0,organic,2018,WestTexNewMexico
18246,9,2018-01-21,1.87,13766.76,1191.92,2452.79,727.94,9394.11,9351.80,42.31,0.0,organic,2018,WestTexNewMexico
18247,10,2018-01-14,1.93,16205.22,1527.63,2981.04,727.01,10969.54,10919.54,50.00,0.0,organic,2018,WestTexNewMexico
18248,11,2018-01-07,1.62,17489.58,2894.77,2356.13,224.53,12014.15,11988.14,26.01,0.0,organic,2018,WestTexNewMexico

In [8]:
# df['4046'] + df['4225'] + df['4770']
8603.62	+ 93.25

8696.87

2026-08-29 10:50:27,050 - ERROR    - Exception occurred while processing request: "Column(s) ['AveragePrice'] do not exist"
Traceback (most recent call last):
  File "c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\dtale\views.py", line 121, in _handle_exceptions
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\dtale\views.py", line 2006, in reshape_data
    instance = startup(data=builder.reshape(), ignore_duplicate=True)
                            ^^^^^^^^^^^^^^^^^
  File "c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\dtale\data_reshapers.py", line 49, in reshape
    return self.builder.reshape(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\dtale\data_reshapers.py", line 166, in reshape
    agg_data = agg_data.aggregate(custom_aggregate_handler(cols))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\groupby\generic.py", line 1432, in aggregate
    result = op.agg()
             ^^^^^^^^
  File "c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\apply.py", line 190, in agg
    return self.agg_dict_like()
           ^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\apply.py", line 423, in agg_dict_like
    return self.agg_or_apply_dict_like(op_name="agg")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\apply.py", line 1608, in agg_or_apply_dict_like
    result_index, result_data = self.compute_dict_like(
                                ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\apply.py", line 462, in compute_dict_like
    func = self.normalize_dictlike_arg(op_name, selected_obj, func)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\apply.py", line 663, in normalize_dictlike_arg
    raise KeyError(f"Column(s) {list(cols)} do not exist")
KeyError: "Column(s) ['AveragePrice'] do not exist"
2026-08-29 10:50:37,455 - ERROR    - Exception occurred while processing request: "Column(s) ['AveragePrice'] do not exist"
Traceback (most recent call last):
  File "c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\dtale\views.py", line 121, in _handle_exceptions
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\dtale\views.py", line 2009, in reshape_data
    data=builder.reshape(), data_id=data_id, ignore_duplicate=True
         ^^^^^^^^^^^^^^^^^
  File "c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\dtale\data_reshapers.py", line 49, in reshape
    return self.builder.reshape(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\dtale\data_reshapers.py", line 166, in reshape
    agg_data = agg_data.aggregate(custom_aggregate_handler(cols))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\groupby\generic.py", line 1432, in aggregate
    result = op.agg()
             ^^^^^^^^
  File "c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\apply.py", line 190, in agg
    return self.agg_dict_like()
           ^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\apply.py", line 423, in agg_dict_like
    return self.agg_or_apply_dict_like(op_name="agg")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\apply.py", line 1608, in agg_or_apply_dict_like
    result_index, result_data = self.compute_dict_like(
                                ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\apply.py", line 462, in compute_dict_like
    func = self.normalize_dictlike_arg(op_name, selected_obj, func)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\apply.py", line 663, in normalize_dictlike_arg
    raise KeyError(f"Column(s) {list(cols)} do not exist")
KeyError: "Column(s) ['AveragePrice'] do not exist"

In [10]:
import dtale as app

app.show(df)